import { createEmptyDocument, type UniversalLegalDocument } from '@/lib/legal-engine/types';

export const SAMPLE_AMPARO_INDIRECTO: UniversalLegalDocument = createEmptyDocument({
  id: 'doc-amparo-801-2024',
  title: 'Demanda de Amparo Indirecto',
  documentType: 'amparo_indirecto',
  documentTypeLabel: 'Amparo Indirecto',
  matter: 'Amparo',
  jurisdiction: 'Cd. de México',
  parties: {
    quejoso: '[QUEJOSO O PROMOVENTE]',
    autoridadResponsable: 'Juez de Distrito / Tribunal Laboral de la CDMX',
    terceroInteresado: '[TERCERO INTERESADO]',
  },
  caseRefs: {
    expediente: '801/2024',
    juzgado: 'Juzgado de Distrito en Materia de Trabajo de la CDMX',
  },
  sections: [
    {
      id: 'sec-proemio',
      type: 'header',
      title: 'I. Proemio y Acreditación de Personalidad',
      order: 1,
      isRepeatable: false,
      isEditable: true,
      isGenerated: true,
      isManuallyEdited: false,
      variables: [],
      validationErrors: [],
      validationWarnings: [],
      content: [
        {
          id: 'blk-proemio-1',
          layer: 'SOURCE_FACT',
          trustLevel: 'VERIFIED',
          text: 'C. JUEZ DE DISTRITO EN MATERIA DE TRABAJO EN LA CIUDAD DE MÉXICO EN TURNO.\n\n[NOMBRE DEL QUEJOSO / PROMOVENTE], por propio derecho (o a través de su representante legal debidamente acreditado), señalando como domicilio para oír y recibir toda clase de notificaciones y documentos el ubicado en [DOMICILIO PROCESAL], y autorizando en términos amplios del artículo 12 de la Ley de Amparo al Licenciado en Derecho [NOMBRE DEL ABOGADO], con cédula profesional número [NÚMERO DE CÉDULA], ante Usted con el debido respeto comparezco para exponer:\n\nQue por medio del presente escrito, con fundamento en los artículos 103, fracción I, y 107, fracciones I y VII, de la Constitución Política de los Estados Unidos Mexicanos, así como en los artículos 1o, 107 y 108 de la Ley de Amparo, vengo a solicitar el AMPARO Y PROTECCIÓN DE LA JUSTICIA DE LA UNIÓN en contra de los actos y autoridades que a continuación se precisan.',
          isManuallyEdited: false,
          style: {
            fontFamily: 'inherit',
            fontSize: '13px',
            textAlign: 'justify',
            lineHeight: '1.6',
          },
        },
      ],
    },
    {
      id: 'sec-antecedentes',
      type: 'background',
      title: 'II. Antecedentes del Acto Reclamado',
      order: 2,
      isRepeatable: false,
      isEditable: true,
      isGenerated: true,
      isManuallyEdited: false,
      variables: [],
      validationErrors: [],
      validationWarnings: [],
      content: [
        {
          id: 'blk-antecedentes-1',
          layer: 'SOURCE_FACT',
          trustLevel: 'VERIFIED',
          text: 'BAJO PROTESTA DE DECIR VERDAD, manifiesto que constituyen antecedentes del acto reclamado los siguientes hechos y abstenciones:\n\n1. Con fecha [FECHA DE RADICACIÓN], el quejoso promovió juicio laboral radicado bajo el número de expediente [EXPEDIENTE PRINCIPAL], ante la autoridad señalada como responsable.\n\n2. Mediante proveído de fecha [FECHA DE RESOLUCIÓN IMPUGNADA], la autoridad responsable emitió resolución interlocutoria mediante la cual determinó desechar la prueba pericial oportunamente ofrecida, bajo el argumento infundado de extemporaneidad procesal.\n\n3. Dicha resolución fue legalmente notificada al quejoso con fecha [FECHA DE NOTIFICACIÓN], por lo que el presente juicio de garantías se promueve dentro del término legal de quince días previsto por el artículo 17 de la Ley de Amparo.',
          isManuallyEdited: false,
          style: {
            fontFamily: 'inherit',
            fontSize: '13px',
            textAlign: 'justify',
            lineHeight: '1.6',
          },
        },
      ],
    },
    {
      id: 'sec-conceptos',
      type: 'argument',
      title: 'III. Conceptos de Violación',
      order: 3,
      isRepeatable: true,
      isEditable: true,
      isGenerated: true,
      isManuallyEdited: false,
      variables: [],
      validationErrors: [],
      validationWarnings: [],
      content: [
        {
          id: 'blk-conceptos-1',
          layer: 'GENERATED_ARGUMENT',
          trustLevel: 'VERIFIED',
          text: 'ÚNICO. VIOLACIÓN A LOS DERECHOS FUNDAMENTALES DE DEBIDO PROCESO, DEFENSA ADECUADA Y TUTELA JUDICIAL EFECTIVA CONSAGRADOS EN LOS ARTÍCULOS 14, 16 Y 17 CONSTITUCIONALES, ASÍ COMO AL ARTÍCULO 8.1 DE LA CONVENCIÓN AMERICANA SOBRE DERECHOS HUMANOS.\n\nLa resolución reclamada transgrede en perjuicio del suscrito el principio de legalidad y debida fundamentación y motivación procesal, toda vez que la autoridad responsable realizó una interpretación restrictiva e indebida de los plazos procesales probatorios.\n\nEn efecto, el derecho de contradicción y ofrecimiento de pruebas constituye una formalidad esencial del procedimiento indispensable para garantizar la defensa adecuada. Al desechar la prueba pericial sin fundar debidamente la supuesta preclusión, la autoridad responsable coloca al quejoso en absoluto estado de indefensión procesal, vulnerando el principio de exhaustividad y congruencia judicial.',
          isManuallyEdited: false,
          style: {
            fontFamily: 'inherit',
            fontSize: '13px',
            textAlign: 'justify',
            lineHeight: '1.6',
          },
        },
      ],
    },
    {
      id: 'sec-petitorios',
      type: 'petition',
      title: 'IV. Puntos Petitorios',
      order: 4,
      isRepeatable: false,
      isEditable: true,
      isGenerated: true,
      isManuallyEdited: false,
      variables: [],
      validationErrors: [],
      validationWarnings: [],
      content: [
        {
          id: 'blk-petitorios-1',
          layer: 'USER_POSITION',
          trustLevel: 'VERIFIED',
          text: 'Por lo anteriormente expuesto y con fundamento en los artículos 103 y 107 constitucionales, así como en los artículos relativos y aplicables de la Ley de Amparo, a ese H. Juzgado de Distrito atentamente solicito:\n\nPRIMERO. Tenerme por presentado en tiempo y forma, solicitando el Amparo y Protección de la Justicia Federal en contra de los actos y autoridades señalados en el presente libelo.\n\nSEGUNDO. Admitir a trámite la presente demanda de amparo indirecto, solicitando a la autoridad responsable su respectivo informe justificado con apercibimiento de ley.\n\nTERCERO. Señalar día y hora para la celebración de la audiencia constitucional.\n\nCUARTO. En su oportunidad procesal, previos trámites de ley, dictar sentencia definitiva en la que se conceda al quejoso el Amparo y Protección de la Justicia de la Unión, restituyéndolo en el pleno goce del derecho fundamental conculcado.',
          isManuallyEdited: false,
          style: {
            fontFamily: 'inherit',
            fontSize: '13px',
            textAlign: 'justify',
            lineHeight: '1.6',
          },
        },
      ],
    },
  ],
  sourceDocuments: [],
  generationMetadata: {
    pipelineState: {
      currentStage: null,
      stages: {} as any,
      isComplete: true,
      hasErrors: false,
    },
    aiUsed: true,
  },
  status: 'draft',
  createdAt: '2024-04-23T10:00:00Z',
  updatedAt: new Date().toISOString(),
});

export function createInitialWritingTemplate(typeLabel: string, matter: string): UniversalLegalDocument {
  return createEmptyDocument({
    id: `doc-${Date.now()}`,
    title: `Demanda de ${typeLabel}`,
    documentType: typeLabel.toLowerCase().replace(/\s+/g, '_'),
    documentTypeLabel: typeLabel,
    matter: matter,
    jurisdiction: 'Cd. de México',
    parties: {
      quejoso: '[NOMBRE DEL ACTOR / QUEJOSO]',
      autoridadResponsable: '[AUTORIDAD RESPONSABLE SEÑALADA]',
      terceroInteresado: '[TERCERO INTERESADO]',
    },
    caseRefs: {
      expediente: 'EN TRÁMITE',
      juzgado: 'Juzgado Competente',
    },
    sections: [
      {
        id: 'sec-encabezado',
        type: 'header',
        title: 'I. Quejoso y Acreditación de Personalidad',
        order: 1,
        isRepeatable: false,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'b-1',
            layer: 'USER_POSITION',
            trustLevel: 'VERIFIED',
            text: 'C. JUEZ DE DISTRITO EN MATERIA DE AMPARO EN TURNO.\n\n[NOMBRE DEL QUEJOSO], promoviendo por mi propio derecho, señalando como domicilio para oír y recibir notificaciones el ubicado en [DOMICILIO PROCESAL] y autorizando en términos del artículo 12 de la Ley de Amparo al Lic. [NOMBRE DEL AUTORIZADO], comparezco a exponer:',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
      {
        id: 'sec-autoridades',
        type: 'identity',
        title: 'II. Autoridad Responsable y Acto Reclamado',
        order: 2,
        isRepeatable: false,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'b-2',
            layer: 'SOURCE_FACT',
            trustLevel: 'VERIFIED',
            text: '1. AUTORIDAD RESPONSABLE: [SEÑALAR ÓRGANO JURISDICCIONAL O ADMINISTRATIVO].\n\n2. ACTO RECLAMADO: La resolución o acto de autoridad de fecha [FECHA DEL ACTO], emitida dentro del expediente [NÚMERO DE EXPEDIENTE].',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
      {
        id: 'sec-conceptos',
        type: 'argument',
        title: 'III. Conceptos de Violación',
        order: 3,
        isRepeatable: true,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'b-3',
            layer: 'GENERATED_ARGUMENT',
            trustLevel: 'VERIFIED',
            text: 'PRIMERO. Violación a la garantía de legalidad y seguridad jurídica (Artículos 14 y 16 Constitucionales). El acto reclamado carece de debida fundamentación y motivación conforme a derecho, vulnerando el principio de exhaustividad.',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
      {
        id: 'sec-petitorios',
        type: 'petition',
        title: 'IV. Puntos Petitorios',
        order: 4,
        isRepeatable: false,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'b-4',
            layer: 'USER_POSITION',
            trustLevel: 'VERIFIED',
            text: 'Por lo expuesto y fundado, a Usted C. Juez atentamente pido:\n\nÚNICO. Tenerme por presentado con este escrito de demanda de amparo, admitirla y en su momento conceder el amparo y protección solicitados.',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
    ],
    sourceDocuments: [],
    generationMetadata: {
      pipelineState: { currentStage: null, stages: {} as any, isComplete: true, hasErrors: false },
      aiUsed: false,
    },
    status: 'draft',
  });
}

export function createResponseResourceTemplate(typeLabel: string, matter: string): UniversalLegalDocument {
  return createEmptyDocument({
    id: `doc-${Date.now()}`,
    title: `Recurso / Contestación: ${typeLabel}`,
    documentType: 'recurso_revision',
    documentTypeLabel: typeLabel,
    matter: matter,
    jurisdiction: 'Cd. de México',
    parties: {
      quejoso: '[RECURRENTE / DEMANDADO]',
      autoridadResponsable: '[AUTORIDAD EMISORA]',
      terceroInteresado: '[CONTRAPARTE]',
    },
    caseRefs: {
      expediente: 'EN TRÁMITE',
      juzgado: 'Tribunal Colegiado de Circuito',
    },
    sections: [
      {
        id: 'sec-proemio-resp',
        type: 'header',
        title: 'I. Proemio y Objeto del Recurso',
        order: 1,
        isRepeatable: false,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'br-1',
            layer: 'USER_POSITION',
            trustLevel: 'VERIFIED',
            text: 'H. TRIBUNAL COLEGIADO DE CIRCUITO EN TURNO (POR CONDUCTO DEL JUEZ DE DISTRITO EMISOR).\n\n[NOMBRE DEL RECURRENTE], en mi carácter de quejoso/tercero interesado dentro del juicio de amparo al rubro indicado, ante Usted con el debido respeto comparezco a interponer formal RECURSO DE REVISIÓN en contra de la sentencia de fecha [FECHA DE SENTENCIA RECURRIDA].',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
      {
        id: 'sec-agravios',
        type: 'argument',
        title: 'II. Expresión de Agravios',
        order: 2,
        isRepeatable: true,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'br-2',
            layer: 'GENERATED_ARGUMENT',
            trustLevel: 'VERIFIED',
            text: 'PRIMER AGRAVIO. Causa agravio a la recurrente el considerando resolutivo de la sentencia impugnada, al haber omitido el juzgador de primer grado el estudio integral y exhaustivo de las pruebas periciales y documentales legalmente desahogadas.',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
      {
        id: 'sec-petitorios-resp',
        type: 'petition',
        title: 'III. Petitorios',
        order: 3,
        isRepeatable: false,
        isEditable: true,
        isGenerated: true,
        isManuallyEdited: false,
        variables: [],
        validationErrors: [],
        validationWarnings: [],
        content: [
          {
            id: 'br-3',
            layer: 'USER_POSITION',
            trustLevel: 'VERIFIED',
            text: 'Por lo expuesto y fundado, a este H. Tribunal Colegiado respetuosamente pido:\n\nPRIMERO. Tenerme por presentado interponiendo en tiempo y forma el presente Recurso de Revisión.\n\nSEGUNDO. Remitir los autos al H. Tribunal Colegiado de Circuito competente para substanciación y resolución.',
            isManuallyEdited: false,
            style: { fontFamily: 'inherit', fontSize: '13px', textAlign: 'justify', lineHeight: '1.6' },
          },
        ],
      },
    ],
    sourceDocuments: [],
    generationMetadata: {
      pipelineState: { currentStage: null, stages: {} as any, isComplete: true, hasErrors: false },
      aiUsed: false,
    },
    status: 'draft',
  });
}
