import { describe, expect, it } from 'vitest';
import { createFederalLegislationAdapter } from '@/lib/legal-engine/legal-research/adapters/federalLegislation';
import { createScjnAdapter } from '@/lib/legal-engine/legal-research/adapters/scjn';
import type { LegalRegimeResolution, LegalResearchRequest, NormalizedResearchQuery } from '@/lib/legal-engine/legal-research/types';
const regime: LegalRegimeResolution = { id: 'r', status: 'RESOLVED', country: { code: 'MX', displayName: 'México' }, scope: 'FEDERAL', temporalPrecision: 'UNKNOWN', fieldEvidence: [], unresolvedFields: [], resolutionHash: 'h' };
const request: LegalResearchRequest = { id: 'q', legalIssueId: 'i', coverageItemIds: [], question: 'q', requestedAuthorityTypes: ['STATUTE'], sourceAuthorityMentionIds: [], contextHash: 'c', regimeResolutionId: 'r', status: 'READY_FOR_RETRIEVAL', createdAt: '2026-01-01T00:00:00.000Z' };
const query: NormalizedResearchQuery = { requestId: 'q', normalizedQuery: 'consulta', queryHash: 'q', explicitTerms: [], regimeHash: 'h' };
function response(body: unknown, type = 'application/json') { return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': type } }); }
describe('official research adapters', () => {
  it('maps federal search and retrieval without hardcoded legal content', async () => { const calls: string[] = []; const adapter = createFederalLegislationAdapter({ searchUrl: 'https://diputados.gob.mx/test/search', fetch: async (input) => { calls.push(String(input)); return calls.length === 1 ? response([{ id: 'a', citation: 'Ley X', url: 'https://diputados.gob.mx/test/a', locator: 'art. 1', authorityType: 'STATUTE', proposition: 'Texto oficial' }]) : new Response('Texto oficial federal', { headers: { 'content-type': 'text/plain' } }); } }); const found = await adapter.search({ request, query, regime }); expect(found.status).toBe('PASS'); const got = await adapter.retrieve({ candidateId: found.candidates[0].id, requestId: request.id }); expect(got.status).toBe('PASS'); expect(got.proposition?.text).toBe('Texto oficial'); expect(calls[0]).toContain('q=consulta'); });
  it('rejects search results outside the official allowlist', async () => { const adapter = createScjnAdapter({ searchUrl: 'https://sjf2.scjn.gob.mx/test/search', fetch: async () => response([{ citation: 'Tesis', url: 'https://evil.example/a', authorityType: 'THESIS', proposition: 'x' }]) }); const result = await adapter.search({ request: { ...request, requestedAuthorityTypes: ['THESIS'] }, query, regime }); expect(result.status).toBe('FAIL'); expect(result.reasons).toContain('OFFICIAL_DOMAIN_NOT_ALLOWED'); });
  it('maps SJF authority type and preserves official detail evidence', async () => { let n = 0; const adapter = createScjnAdapter({ searchUrl: 'https://sjf2.scjn.gob.mx/test/search', fetch: async () => ++n === 1 ? response([{ id: 't', citation: 'Tesis 1', url: 'https://sjf2.scjn.gob.mx/test/t', authorityType: 'THESIS', proposition: 'Criterio oficial' }]) : new Response('documento SJF', { headers: { 'content-type': 'text/plain' } }) }); const found = await adapter.search({ request: { ...request, requestedAuthorityTypes: ['THESIS'] }, query, regime }); const got = await adapter.retrieve({ candidateId: found.candidates[0].id, requestId: request.id }); expect(got.candidate?.authorityType).toBe('THESIS'); expect(got.evidence?.sourceDomain).toBe('sjf2.scjn.gob.mx'); });
});
