import { ClassificationResult, RequiredInput } from './types';

interface DocTypeRule {
  pattern: RegExp[];
  documentType: string;
  documentTypeLabel: string;
  matter: string;
  jurisdiction: string;
  proceduralStage: string;
  authority?: string;
  objective: string;
  requiredInputs: RequiredInput[];
}

export const NEEDS_DOCUMENT_TYPE_SELECTION = 'NEEDS_DOCUMENT_TYPE_SELECTION' as const;

const DEMAND_SUBTYPE_PATTERN = '(?:ordinari[ao]|ejecutiv[ao]|oral|especial|hipotecari[ao]|prendari[ao]|arrendamiento|usucapi[oó]n|reivindicatoria|rescisi[oó]n|cumplimiento)';

function demandWithoutSubtypePattern(matter: 'civil' | 'mercantil'): RegExp {
  return new RegExp(
    `^(?![\\s\\S]*\\b${DEMAND_SUBTYPE_PATTERN}\\b)(?=[\\s\\S]*\\bdemanda\\b)(?=[\\s\\S]*\\b${matter}\\b)[\\s\\S]*$`,
    'i',
  );
}

const CATALOGED_DEMAND_SUBTYPE_RULES: DocTypeRule[] = [
  ['civil', 'ordinaria', 'demanda_ordinaria_civil', 'Demanda Ordinaria Civil'],
  ['civil', 'ejecutiva', 'demanda_ejecutiva_civil', 'Demanda Ejecutiva Civil'],
  ['civil', 'oral', 'demanda_oral_civil', 'Demanda Oral Civil'],
  ['mercantil', 'ordinaria', 'demanda_ordinaria_mercantil', 'Demanda Ordinaria Mercantil'],
  ['mercantil', 'ejecutiva', 'demanda_ejecutiva_mercantil', 'Demanda Ejecutiva Mercantil'],
  ['mercantil', 'oral', 'demanda_oral_mercantil', 'Demanda Oral Mercantil'],
].map(([matter, subtype, documentType, documentTypeLabel]) => ({
  pattern: [new RegExp(`(?=[\\s\\S]*\\b(?:demanda|juicio)\\b)(?=[\\s\\S]*\\b${subtype}\\b)(?=[\\s\\S]*\\b${matter}\\b)[\\s\\S]*$`, 'i')],
  documentType,
  documentTypeLabel,
  matter,
  jurisdiction: 'local',
  proceduralStage: 'inicial',
  objective: `Preparar ${documentTypeLabel.toLowerCase()}`,
  requiredInputs: [],
}));

export const DOC_TYPE_RULES: DocTypeRule[] = [
  {
    pattern: [
      /revisi[oó]n\s+extraordinaria.*amparo.*directo/i,
      /contestaci[oó]n.*sentencia.*amparo.*directo/i,
      /respuesta.*sentencia.*amparo.*directo/i,
    ],
    documentType: 'contestacion_revision_extraordinaria_amparo_directo',
    documentTypeLabel: 'Contestación / Revisión extraordinaria ante sentencia de amparo directo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'post-sentencia',
    objective: 'Plantear una respuesta extraordinaria frente a una sentencia de amparo directo, sujeta a verificación de procedencia',
    requiredInputs: [],
  },
  {
    pattern: [/recurso.*revisi[oó]n.*amparo.*directo/i, /revisi[oó]n.*en.*amparo.*directo/i],
    documentType: 'recurso_revision_amparo_directo',
    documentTypeLabel: 'Recurso de Revisión en Amparo Directo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    authority: 'Suprema Corte de Justicia de la Nación',
    objective: 'Impugnar sentencia de amparo directo por cuestiones de constitucionalidad',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*queja/i, /queja/i],
    documentType: 'recurso_queja',
    documentTypeLabel: 'Recurso de Queja',
    matter: 'general',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Impugnar resoluciones que no admiten revisión',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*reclamaci[oó]n/i, /reclamaci[oó]n/i],
    documentType: 'recurso_reclamacion',
    documentTypeLabel: 'Recurso de Reclamación',
    matter: 'general',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Impugnar acuerdos de trámite',
    requiredInputs: []
  },
  // ── MATERIA CONSTITUCIONAL Y AMPARO EXTENDIDO ──────────────────────────────
  {
    pattern: [/ampliaci[oó]n.*demanda.*amparo/i, /ampliaci[oó]n.*de.*amparo/i],
    documentType: 'ampliacion_demanda_amparo',
    documentTypeLabel: 'Ampliación de Demanda de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'ampliacion',
    objective: 'Ampliar la demanda de amparo respecto de nuevos actos reclamados o autoridades',
    requiredInputs: []
  },
  {
    pattern: [/amparo\s+adhesivo/i, /adhesi[oó]n.*amparo/i],
    documentType: 'amparo_adhesivo',
    documentTypeLabel: 'Amparo Adhesivo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'adhesivo',
    objective: 'Adherirse al amparo directo promovido por la contraria',
    requiredInputs: []
  },
  {
    pattern: [/suspensi[oó]n\s+provisional/i, /solicitud.*suspensi[oó]n\s+provisional/i],
    documentType: 'solicitud_suspension_provisional',
    documentTypeLabel: 'Solicitud de Suspensión Provisional',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'cautelar',
    objective: 'Solicitar la suspensión provisional en el incidente de amparo',
    requiredInputs: []
  },
  {
    pattern: [/suspensi[oó]n\s+definitiva/i, /audiencia\s+incidental.*suspensi[oó]n/i],
    documentType: 'solicitud_suspension_definitiva',
    documentTypeLabel: 'Solicitud de Suspensión Definitiva',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'cautelar',
    objective: 'Solicitar la concesión de suspensión definitiva en la audiencia incidental',
    requiredInputs: []
  },
  {
    pattern: [/alegatos.*amparo/i],
    documentType: 'alegatos_amparo',
    documentTypeLabel: 'Alegatos de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'alegatos',
    objective: 'Formular alegatos en el juicio de amparo',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*revisi[oó]n.*amparo(?!.*directo)/i, /revisi[oó]n.*amparo.*indirecto/i],
    documentType: 'recurso_revision_amparo',
    documentTypeLabel: 'Recurso de Revisión de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Impugnar sentencia de amparo indirecto en segunda instancia',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*queja.*amparo/i, /queja.*de.*amparo/i, /queja.*ley\s+de\s+amparo/i],
    documentType: 'recurso_queja_amparo',
    documentTypeLabel: 'Recurso de Queja de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Interponer recurso de queja en materia de amparo',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*reclamaci[oó]n.*amparo/i, /reclamaci[oó]n.*amparo/i],
    documentType: 'recurso_reclamacion_amparo',
    documentTypeLabel: 'Recurso de Reclamación de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Impugnar auto de presidencia en juicio de amparo',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*inconformidad.*amparo/i, /inconformidad.*amparo/i],
    documentType: 'recurso_inconformidad_amparo',
    documentTypeLabel: 'Recurso de Inconformidad de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Impugnar auto que tiene por cumplida la ejecutoria de amparo',
    requiredInputs: []
  },
  {
    pattern: [/cumplimiento.*ejecutoria.*amparo/i, /acatamiento.*ejecutoria.*amparo/i],
    documentType: 'cumplimiento_ejecutoria_amparo',
    documentTypeLabel: 'Cumplimiento de Ejecutoria de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'ejecucion',
    objective: 'Acreditar el cumplimiento de la ejecutoria de amparo',
    requiredInputs: []
  },
  {
    pattern: [/promoci[oó]n.*cumplimiento.*amparo/i, /requerimiento.*cumplimiento.*ejecutoria/i],
    documentType: 'promocion_cumplimiento_amparo',
    documentTypeLabel: 'Promoción de Cumplimiento de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'ejecucion',
    objective: 'Solicitar requerimiento forzoso de cumplimiento de ejecutoria',
    requiredInputs: []
  },
  {
    pattern: [/manifestaciones.*cumplimiento.*amparo/i, /desahogo.*vista.*cumplimiento.*amparo/i],
    documentType: 'manifestaciones_cumplimiento_amparo',
    documentTypeLabel: 'Manifestaciones sobre Cumplimiento de Amparo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'ejecucion',
    objective: 'Desahogar vista sobre pretendido cumplimiento de la ejecutoria',
    requiredInputs: []
  },
  // ── MATERIA LABORAL ────────────────────────────────────────────────────────
  {
    pattern: [/amparo\s+indirecto.*laboral/i, /amparo.*laboral.*indirecto/i, /demanda.*amparo.*indirecto.*laboral/i, /\bamparo\b.*?\bindirecto\b.*?\blaboral\b/i],
    documentType: 'demanda_amparo_indirecto_laboral',
    documentTypeLabel: 'Demanda de Amparo Indirecto Laboral',
    matter: 'laboral',
    jurisdiction: 'federal',
    proceduralStage: 'cautelar',
    objective: 'Promover juicio de amparo indirecto en materia laboral',
    requiredInputs: []
  },
  {
    pattern: [/amparo\s+directo.*laboral/i, /amparo.*laboral.*directo/i, /demanda.*amparo.*directo.*laboral/i, /\bamparo\b.*?\bdirecto\b.*?\blaboral\b/i],
    documentType: 'demanda_amparo_directo_laboral',
    documentTypeLabel: 'Demanda de Amparo Directo Laboral',
    matter: 'laboral',
    jurisdiction: 'federal',
    proceduralStage: 'constitucional',
    objective: 'Promover juicio de amparo directo contra laudo o sentencia definitiva laboral',
    requiredInputs: []
  },
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:a\s+la\s+)?reconvenci[oó]n.*laboral/i, /reconvenci[oó]n.*laboral.*(?:contestaci[oó]n|contestar)/i, /desahogo.*reconvenci[oó]n.*laboral/i],
    documentType: 'contestacion_reconvencion_laboral',
    documentTypeLabel: 'Contestación a la Reconvención Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Dar contestación a la reconvención formulada en juicio laboral',
    requiredInputs: []
  },
  {
    pattern: [/reconvenci[oó]n.*laboral/i, /contrademanda.*laboral/i, /reconvenci[oó]n.*trabajo/i],
    documentType: 'reconvencion_laboral',
    documentTypeLabel: 'Reconvención Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Formular demanda reconvencional o contrademanda en juicio laboral',
    requiredInputs: []
  },
  {
    pattern: [/ampliaci[oó]n.*(?:de\s+)?demanda.*laboral/i, /ampliar.*demanda.*laboral/i, /ampliaci[oó]n.*laboral/i],
    documentType: 'ampliacion_demanda_laboral',
    documentTypeLabel: 'Ampliación de Demanda Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Formular ampliación o modificación de demanda laboral',
    requiredInputs: []
  },
  {
    pattern: [/objeci[oó]n.*pruebas?.*laboral/i, /objetar.*pruebas?.*laboral/i, /impugnaci[oó]n.*pruebas?.*laboral/i],
    documentType: 'objecion_pruebas_laboral',
    documentTypeLabel: 'Objeción de Pruebas Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Objetar pruebas ofrecidas por la contraparte en juicio laboral',
    requiredInputs: []
  },
  {
    pattern: [/ofrecimiento.*pruebas?.*laboral/i, /ofrecer.*pruebas?.*laboral/i, /pruebas?.*laboral(?:es)?/i],
    documentType: 'ofrecimiento_pruebas_laboral',
    documentTypeLabel: 'Ofrecimiento de Pruebas Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Ofrecer medios probatorios en juicio ordinario laboral',
    requiredInputs: []
  },
  {
    pattern: [/desahogo.*prevenci[oó]n.*laboral/i, /aclaraci[oó]n.*demanda.*laboral/i, /cumplir.*prevenci[oó]n.*laboral/i, /preven.*laboral/i],
    documentType: 'desahogo_prevencion_laboral',
    documentTypeLabel: 'Desahogo de Prevención Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Desahogar prevención formulada por el tribunal laboral',
    requiredInputs: []
  },
  {
    pattern: [/alegatos.*laboral(?:es)?/i, /conclusiones.*laboral(?:es)?/i],
    documentType: 'alegatos_laborales',
    documentTypeLabel: 'Alegatos Laborales',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Formular alegatos de clausura en juicio laboral',
    requiredInputs: []
  },
  {
    pattern: [/cumplimiento.*(?:laudo|sentencia).*laboral/i, /manifestar.*cumplimiento.*laboral/i, /acreditamiento.*cumplimiento.*laudo/i],
    documentType: 'cumplimiento_laudo_sentencia_laboral',
    documentTypeLabel: 'Cumplimiento de Laudo o Sentencia Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'ejecucion',
    objective: 'Acreditar o manifestar sobre el cumplimiento voluntario de laudo o sentencia laboral',
    requiredInputs: []
  },
  {
    pattern: [/ejecuci[oó]n.*(?:laudo|sentencia).*laboral/i, /solicitud.*ejecuci[oó]n.*laboral/i, /embargo.*laboral/i, /ejecuci[oó]n.*forzosa.*laboral/i],
    documentType: 'ejecucion_sentencia_laboral',
    documentTypeLabel: 'Ejecución de Sentencia Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'ejecucion',
    objective: 'Solicitar ejecución forzosa y requerimiento de pago o embargo de laudo laboral',
    requiredInputs: []
  },
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:demanda)?.*laboral/i, /laboral.*(?:contestaci[oó]n|contestar)/i, /contestar.*laboral/i, /contestaci[oó]n.*laboral/i],
    documentType: 'contestacion_demanda_laboral',
    documentTypeLabel: 'Contestación de Demanda Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Dar contestación a demanda laboral',
    requiredInputs: []
  },
  {
    pattern: [/demanda.*laboral/i, /juicio.*laboral/i, /despido.*injustificado/i, /demanda.*despido/i, /reclamo.*laboral/i],
    documentType: 'demanda_laboral',
    documentTypeLabel: 'Demanda Laboral',
    matter: 'laboral',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Promover demanda individual de trabajo ante tribunal laboral',
    requiredInputs: []
  },
  {
    pattern: [/demanda.*amparo.*indirecto/i, /amparo.*indirecto/i],
    documentType: 'demanda_amparo_indirecto',
    documentTypeLabel: 'Demanda de Amparo Indirecto',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'inicial',
    objective: 'Solicitar protección de la justicia federal contra actos de autoridad',
    requiredInputs: []
  },
  {
    pattern: [/demanda.*amparo.*directo/i, /amparo.*directo/i],
    documentType: 'demanda_amparo_directo',
    documentTypeLabel: 'Demanda de Amparo Directo',
    matter: 'constitucional',
    jurisdiction: 'federal',
    proceduralStage: 'inicial',
    objective: 'Impugnar sentencias definitivas',
    requiredInputs: []
  },
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:demanda)?.*civil/i, /civil.*(?:contestaci[oó]n|contestar)/i],
    documentType: 'contestacion_demanda_civil',
    documentTypeLabel: 'Contestación de Demanda Civil',
    matter: 'civil',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Dar contestación a demanda civil',
    requiredInputs: []
  },
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:demanda)?.*mercantil/i, /mercantil.*(?:contestaci[oó]n|contestar)/i],
    documentType: 'contestacion_demanda_mercantil',
    documentTypeLabel: 'Contestación de Demanda Mercantil',
    matter: 'mercantil',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Dar contestación a demanda mercantil',
    requiredInputs: []
  },
  // ── MATERIA FAMILIAR ──────────────────────────────────────────────────────
  // ── MATERIA FAMILIAR — 1. Contestaciones Especializadas (prioridad alta) ──
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:demanda)?.*divorcio/i, /divorcio.*(?:contestaci[oó]n|contestar)/i],
    documentType: 'contestacion_divorcio',
    documentTypeLabel: 'Contestación de Divorcio',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Contestar demanda de divorcio y proponer contrapropuesta de convenio',
    requiredInputs: []
  },
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:demanda)?.*(?:alimentos|pensi[oó]n)/i, /(?:alimentos|pensi[oó]n).*(?:contestaci[oó]n|contestar)/i],
    documentType: 'contestacion_alimentos',
    documentTypeLabel: 'Contestación de Alimentos',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Contestar demanda de pensión alimenticia',
    requiredInputs: []
  },
  {
    pattern: [/(?:contestaci[oó]n|contestar).*(?:demanda)?.*(?:guarda|custodia)/i, /(?:guarda|custodia).*(?:contestaci[oó]n|contestar)/i],
    documentType: 'contestacion_guarda_custodia',
    documentTypeLabel: 'Contestación de Guarda y Custodia',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Contestar demanda de guarda y custodia',
    requiredInputs: []
  },

  // ── MATERIA FAMILIAR — 2. Ejecución y Recursos ─────────────────────────────
  {
    pattern: [/ejecuci[oó]n.*(?:convenio|sentencia)?.*familiar/i],
    documentType: 'ejecucion_convenio_familiar',
    documentTypeLabel: 'Ejecución de Convenio Familiar',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'ejecucion',
    objective: 'Ejecutar forzosamente convenio o sentencia familiar',
    requiredInputs: []
  },
  {
    pattern: [/apelaci[oó]n.*familiar/i, /recurso.*apelaci[oó]n.*familiar/i],
    documentType: 'apelacion_familiar',
    documentTypeLabel: 'Apelación Familiar',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'recurso',
    objective: 'Interponer apelación en materia familiar',
    requiredInputs: []
  },
  {
    pattern: [/alegatos.*familiar/i, /conclusiones.*familiar/i],
    documentType: 'alegatos_familiar',
    documentTypeLabel: 'Alegatos Familiares',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'instruccion',
    objective: 'Formular alegatos y conclusiones en juicio familiar',
    requiredInputs: []
  },

  // ── MATERIA FAMILIAR — 3. Incidentes y Modificaciones ──────────────────────
  {
    pattern: [/incidente.*modificaci[oó]n.*pensi[oó]n/i, /modificaci[oó]n.*pensi[oó]n.*alimenticia/i],
    documentType: 'incidente_modificacion_pension',
    documentTypeLabel: 'Incidente de Modificación de Pensión',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'incidental',
    objective: 'Modificar monto de pensión alimenticia fijada en sentencia',
    requiredInputs: []
  },
  {
    pattern: [/incidente.*reducci[oó]n.*pensi[oó]n/i, /reducci[oó]n.*pensi[oó]n/i, /disminuci[oó]n.*pensi[oó]n/i],
    documentType: 'incidente_reduccion_pension',
    documentTypeLabel: 'Incidente de Reducción de Pensión',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'incidental',
    objective: 'Reducir monto de pensión alimenticia',
    requiredInputs: []
  },
  {
    pattern: [/incidente.*incremento.*pensi[oó]n/i, /incremento.*pensi[oó]n/i, /aumento.*pensi[oó]n/i],
    documentType: 'incidente_incremento_pension',
    documentTypeLabel: 'Incidente de Incremento de Pensión',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'incidental',
    objective: 'Incrementar monto de pensión alimenticia',
    requiredInputs: []
  },
  {
    pattern: [/modificaci[oó]n.*convivencia/i, /cambio.*r[eé]gimen.*visitas/i],
    documentType: 'modificacion_convivencias',
    documentTypeLabel: 'Modificación de Convivencias',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'incidental',
    objective: 'Modificar régimen de convivencias vigente',
    requiredInputs: []
  },
  {
    pattern: [/liquidaci[oó]n.*sociedad.*conyugal/i, /partici[oó]n.*bienes.*conyugales/i],
    documentType: 'liquidacion_sociedad_conyugal',
    documentTypeLabel: 'Liquidación de Sociedad Conyugal',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'incidental',
    objective: 'Liquidar el patrimonio de la sociedad conyugal',
    requiredInputs: []
  },

  // ── MATERIA FAMILIAR — 4. Demandas, Medidas, Convenios y Actos No Contenciosos ──
  {
    pattern: [/demanda.*divorcio/i, /divorcio.*incausado/i, /solicitud.*divorcio/i],
    documentType: 'demanda_divorcio',
    documentTypeLabel: 'Demanda de Divorcio',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Iniciar procedimiento de divorcio incausado',
    requiredInputs: []
  },
  {
    pattern: [/convenio.*divorcio/i, /propuesta.*convenio.*divorcio/i],
    documentType: 'convenio_divorcio',
    documentTypeLabel: 'Convenio de Divorcio',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Presentar propuesta de convenio regulador de divorcio',
    requiredInputs: []
  },
  {
    pattern: [/demanda.*alimentos/i, /juicio.*alimentos/i, /fijaci[oó]n.*pensi[oó]n.*alimenticia/i],
    documentType: 'demanda_alimentos',
    documentTypeLabel: 'Demanda de Alimentos',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Demandar fijación y pago de pensión alimenticia',
    requiredInputs: []
  },
  {
    pattern: [/alimentos.*provisionales/i, /pensi[oó]n.*provisional/i],
    documentType: 'solicitud_alimentos_provisionales',
    documentTypeLabel: 'Solicitud de Alimentos Provisionales',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Solicitar medida provisional urgente de pensión alimenticia',
    requiredInputs: []
  },
  {
    pattern: [/demanda.*(?:guarda|custodia)/i, /juicio.*custodia/i],
    documentType: 'demanda_guarda_custodia',
    documentTypeLabel: 'Demanda de Guarda y Custodia',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Reclamar guarda y custodia de menores',
    requiredInputs: []
  },
  {
    pattern: [/demanda.*convivencia/i, /r[eé]gimen.*convivencia/i, /visitas.*convivencias/i],
    documentType: 'demanda_regimen_convivencias',
    documentTypeLabel: 'Demanda de Régimen de Convivencias',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Fijar régimen judicial de visitas y convivencias',
    requiredInputs: []
  },
  {
    pattern: [/p[eé]rdida.*patria.*potestad/i],
    documentType: 'perdida_patria_potestad',
    documentTypeLabel: 'Pérdida de la Patria Potestad',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Demandar pérdida de la patria potestad',
    requiredInputs: []
  },
  {
    pattern: [/reconocimiento.*paternidad/i, /investigaci[oó]n.*paternidad/i],
    documentType: 'reconocimiento_paternidad',
    documentTypeLabel: 'Reconocimiento de Paternidad',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Reclamar judicialmente el reconocimiento de paternidad',
    requiredInputs: []
  },
  {
    pattern: [/desconocimiento.*paternidad/i, /impugnaci[oó]n.*paternidad/i, /contradicci[oó]n.*paternidad/i],
    documentType: 'desconocimiento_paternidad',
    documentTypeLabel: 'Desconocimiento de Paternidad',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Impugnar presunción o registro de paternidad',
    requiredInputs: []
  },
  {
    pattern: [/adopci[oó]n/i],
    documentType: 'adopcion',
    documentTypeLabel: 'Adopción',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Tramitar juicio o diligencias de adopción',
    requiredInputs: []
  },
  {
    pattern: [/medidas.*protecci[oó]n.*familiar/i, /[oó]rden(?:es)?.*protecci[oó]n.*familiar/i, /violencia.*familiar.*protecci[oó]n/i],
    documentType: 'medidas_proteccion_familiar',
    documentTypeLabel: 'Medidas de Protección Familiar',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'cautelar',
    objective: 'Solicitar medidas cautelares y órdenes de protección familiar',
    requiredInputs: []
  },
  {
    pattern: [/convenio.*familiar/i, /acuerdo.*familiar/i],
    documentType: 'convenio_familiar',
    documentTypeLabel: 'Convenio Familiar',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Someter convenio familiar a aprobación judicial',
    requiredInputs: []
  },
  {
    pattern: [/jurisdicci[oó]n.*voluntaria.*familiar/i, /voluntari[ao].*familiar/i],
    documentType: 'jurisdiccion_voluntaria_familiar',
    documentTypeLabel: 'Jurisdicción Voluntaria Familiar',
    matter: 'familiar',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Promover diligencias no contenciosas en materia familiar',
    requiredInputs: []
  },
  // ── MATERIA ADMINISTRATIVA Y FISCAL ─────────────────────────────────────────
  {
    pattern: [/contestaci[oó]n.*ampliaci[oó]n.*fiscal/i],
    documentType: 'contestacion_ampliacion_fiscal',
    documentTypeLabel: 'Contestación a la Ampliación de Demanda Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'instruccion',
    objective: 'Contestar ampliación de demanda fiscal ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/contestaci[oó]n.*ampliaci[oó]n.*nulidad(?!.*fiscal)/i],
    documentType: 'contestacion_ampliacion_nulidad',
    documentTypeLabel: 'Contestación a la Ampliación de Demanda de Nulidad',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'instruccion',
    objective: 'Contestar ampliación de demanda de nulidad ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/contestaci[oó]n.*(?:nulidad.*fiscal|demanda.*fiscal)/i, /contestar.*(?:nulidad|demanda).*fiscal/i],
    documentType: 'contestacion_nulidad_fiscal',
    documentTypeLabel: 'Contestación de Demanda de Nulidad Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'instruccion',
    objective: 'Contestar demanda de nulidad fiscal ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/contestaci[oó]n.*(?:nulidad.*administrativ|contencioso.*administrativ|demanda.*administrativ)/i, /contestar.*(?:nulidad|demanda).*administrativ/i],
    documentType: 'contestacion_nulidad_administrativa',
    documentTypeLabel: 'Contestación de Demanda de Nulidad Administrativa',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'instruccion',
    objective: 'Dar contestación a demanda de nulidad administrativa ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/ampliaci[oó]n.*demanda.*fiscal/i, /ampliaci[oó]n.*nulidad.*fiscal/i],
    documentType: 'ampliacion_demanda_fiscal',
    documentTypeLabel: 'Ampliación de Demanda de Nulidad Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'ampliacion',
    objective: 'Ampliar demanda de nulidad fiscal ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/ampliaci[oó]n.*demanda.*nulidad(?!.*fiscal)/i, /ampliaci[oó]n.*nulidad.*administrativ/i],
    documentType: 'ampliacion_demanda_nulidad',
    documentTypeLabel: 'Ampliación de Demanda de Nulidad',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'ampliacion',
    objective: 'Ampliar demanda de nulidad administrativa ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/alegatos.*(?:fiscal|sat|cr[eé]dito)/i, /conclusiones.*fiscal/i],
    documentType: 'alegatos_fiscales',
    documentTypeLabel: 'Alegatos Fiscales',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'alegatos',
    objective: 'Formular alegatos en juicio contencioso fiscal',
    requiredInputs: [],
  },
  {
    pattern: [/alegatos.*administrativ/i, /conclusiones.*administrativ/i],
    documentType: 'alegatos_administrativos',
    documentTypeLabel: 'Alegatos Administrativos',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'alegatos',
    objective: 'Formular alegatos en juicio contencioso administrativo',
    requiredInputs: [],
  },
  {
    pattern: [/suspensi[oó]n.*(?:fiscal|pae|ejecuci[oó]n.*fiscal)/i, /solicitud.*suspensi[oó]n.*(?:fiscal|pae|ejecuci[oó]n.*fiscal)/i],
    documentType: 'solicitud_suspension_fiscal',
    documentTypeLabel: 'Solicitud de Suspensión Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'cautelar',
    objective: 'Solicitar suspensión del cobro o PAE fiscal ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/suspensi[oó]n.*acto.*administrativ(?!.*fiscal)/i, /solicitud.*suspensi[oó]n.*(?:acto.*)?administrativ(?!.*fiscal)/i],
    documentType: 'solicitud_suspension_acto_administrativo',
    documentTypeLabel: 'Solicitud de Suspensión del Acto Administrativo',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'cautelar',
    objective: 'Solicitar suspensión del acto administrativo ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/recurso.*revocaci[oó]n.*fiscal/i, /revocaci[oó]n.*fiscal/i, /recurso.*revocaci[oó]n.*cff/i, /revocaci[oó]n.*sat/i],
    documentType: 'recurso_revocacion_fiscal',
    documentTypeLabel: 'Recurso de Revocación Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Interponer recurso de revocación fiscal en sede administrativa',
    requiredInputs: [],
  },
  {
    pattern: [/recurso.*revisi[oó]n.*fiscal/i, /revisi[oó]n.*fiscal/i],
    documentType: 'recurso_revision_fiscal',
    documentTypeLabel: 'Recurso de Revisión Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Interponer revisión fiscal ante Tribunal Colegiado de Circuito',
    requiredInputs: [],
  },
  {
    pattern: [/recurso.*revisi[oó]n.*administrativ(?!.*impi)/i, /revisi[oó]n.*administrativ(?!.*impi)/i],
    documentType: 'recurso_revision_administrativa',
    documentTypeLabel: 'Recurso de Revisión Administrativa',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Interponer revisión administrativa ante Sala Superior del TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/cumplimiento.*sentencia.*fiscal/i],
    documentType: 'cumplimiento_sentencia_fiscal',
    documentTypeLabel: 'Cumplimiento de Sentencia Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'ejecucion',
    objective: 'Promover cumplimiento de sentencia fiscal definitiva',
    requiredInputs: [],
  },
  {
    pattern: [/cumplimiento.*sentencia.*administrativ/i],
    documentType: 'cumplimiento_sentencia_administrativa',
    documentTypeLabel: 'Cumplimiento de Sentencia Administrativa',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'ejecucion',
    objective: 'Promover cumplimiento de sentencia del TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/escrito.*autoridad.*fiscal/i, /promoci[oó]n.*autoridad.*fiscal/i, /escrito.*sat/i, /solicitud.*sat/i],
    documentType: 'escritos_ante_autoridad_fiscal',
    documentTypeLabel: 'Escritos ante Autoridad Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'inicial',
    objective: 'Presentar promoción o solicitud formal ante la autoridad fiscal',
    requiredInputs: [],
  },
  {
    pattern: [/demanda.*nulidad.*fiscal/i, /juicio.*nulidad.*fiscal/i, /nulidad.*cr[eé]dito.*fiscal/i],
    documentType: 'demanda_nulidad_fiscal',
    documentTypeLabel: 'Demanda de Nulidad Fiscal',
    matter: 'fiscal',
    jurisdiction: 'federal',
    proceduralStage: 'inicial',
    objective: 'Demandar nulidad de crédito o resolución fiscal ante el TFJA',
    requiredInputs: [],
  },
  {
    pattern: [/demanda.*nulidad.*administrativ/i, /juicio.*nulidad.*administrativ/i, /nulidad.*administrativ/i],
    documentType: 'demanda_nulidad_administrativa',
    documentTypeLabel: 'Demanda de Nulidad Administrativa',
    matter: 'administrativo',
    jurisdiction: 'federal',
    proceduralStage: 'inicial',
    objective: 'Demandar la nulidad de acto administrativo ante el TFJA',
    requiredInputs: [],
  },
  // ── MATERIA PENAL ───────────────────────────────────────────────────────────
  {
    pattern: [/ampliaci[oó]n.*denuncia/i],
    documentType: 'ampliacion_denuncia',
    documentTypeLabel: 'Ampliación de Denuncia',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Ampliar la denuncia de hechos en carpeta de investigación',
    requiredInputs: [],
  },
  {
    pattern: [/ampliaci[oó]n.*querella/i],
    documentType: 'ampliacion_querella',
    documentTypeLabel: 'Ampliación de Querella',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Ampliar querella penal ante el Ministerio Público',
    requiredInputs: [],
  },
  {
    pattern: [/denuncia.*penal/i, /denuncia.*hechos/i, /denuncia.*ministerio.*p[uú]blico/i, /presentar.*denuncia/i, /^denuncia$/i],
    documentType: 'denuncia',
    documentTypeLabel: 'Denuncia Penal',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Formular denuncia penal ante el Ministerio Público',
    requiredInputs: [],
  },
  {
    pattern: [/querella.*penal/i, /querella.*ministerio.*p[uú]blico/i, /presentar.*querella/i, /^querella$/i],
    documentType: 'querella',
    documentTypeLabel: 'Querella Penal',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Formular querella de parte ofendida ante el Ministerio Público',
    requiredInputs: [],
  },
  {
    pattern: [/asesor.*jur[ií]dico/i, /intervenci[oó]n.*asesor/i],
    documentType: 'escrito_asesor_juridico',
    documentTypeLabel: 'Escrito del Asesor Jurídico',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Acreditar comparecencia e intervención técnica del Asesor Jurídico',
    requiredInputs: [],
  },
  {
    pattern: [/defensa.*penal/i, /defensa.*t[eé]cnica/i, /designaci[oó]n.*defensor/i, /nombramiento.*defensor/i],
    documentType: 'escrito_defensa',
    documentTypeLabel: 'Escrito de Defensa Técnica',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Acreditar defensa técnica del imputado y nombramiento formal',
    requiredInputs: [],
  },
  {
    pattern: [/actos?.*investigaci[oó]n/i, /solicitud.*diligencias?.*investigaci[oó]n/i],
    documentType: 'solicitud_actos_investigacion',
    documentTypeLabel: 'Solicitud de Actos de Investigación',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Solicitar diligencias de investigación al Ministerio Público',
    requiredInputs: [],
  },
  {
    pattern: [/acceso.*carpeta/i, /consulta.*carpeta.*investigaci[oó]n/i, /acceso.*registros.*investigaci[oó]n/i],
    documentType: 'solicitud_acceso_carpeta',
    documentTypeLabel: 'Solicitud de Acceso a Carpeta',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Solicitar acceso y consulta a la carpeta de investigación',
    requiredInputs: [],
  },
  {
    pattern: [/copias?.*carpeta/i, /copias?.*investigaci[oó]n/i],
    documentType: 'solicitud_copias_carpeta',
    documentTypeLabel: 'Solicitud de Copias de Carpeta',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'investigacion',
    objective: 'Solicitar copias de las constancias de la carpeta de investigación',
    requiredInputs: [],
  },
  {
    pattern: [/medidas?.*protecci[oó]n.*penal/i, /medidas?.*protecci[oó]n.*v[ií]ctima/i, /[oó]rdenes?.*protecci[oó]n.*penal/i],
    documentType: 'solicitud_medida_proteccion',
    documentTypeLabel: 'Solicitud de Medidas de Protección',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'cautelar',
    objective: 'Solicitar medidas urgentes de protección para la víctima',
    requiredInputs: [],
  },
  {
    pattern: [/coadyuvancia.*penal/i, /coadyuvancia.*acusaci[oó]n/i, /escrito.*coadyuvante/i],
    documentType: 'escrito_coadyuvancia',
    documentTypeLabel: 'Escrito de Coadyuvancia',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'intermedia',
    objective: 'Constituirse en coadyuvante del Ministerio Público en la acusación',
    requiredInputs: [],
  },
  {
    pattern: [/apelaci[oó]n.*penal/i, /apelaci[oó]n.*cnpp/i, /apelar.*auto.*vinculaci[oó]n/i],
    documentType: 'apelacion_penal',
    documentTypeLabel: 'Recurso de Apelación Penal',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'recurso',
    objective: 'Interponer recurso de apelación penal conforme al CNPP',
    requiredInputs: [],
  },
  {
    pattern: [/revocaci[oó]n.*penal/i, /revocaci[oó]n.*cnpp/i],
    documentType: 'revocacion_penal',
    documentTypeLabel: 'Recurso de Revocación Penal',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'recurso',
    objective: 'Interponer recurso de revocación penal contra auto de trámite',
    requiredInputs: [],
  },
  {
    pattern: [/ejecuci[oó]n.*penal/i, /juez.*ejecuci[oó]n.*penas/i, /beneficio.*preliberacional/i, /libertad.*condicionada/i],
    documentType: 'escrito_ejecucion_penal',
    documentTypeLabel: 'Escrito de Ejecución Penal',
    matter: 'penal',
    jurisdiction: 'local',
    proceduralStage: 'ejecucion',
    objective: 'Promover solicitud ante el Juez de Ejecución Penal',
    requiredInputs: [],
  },
  // ── MATERIA AGRARIA ─────────────────────────────────────────────────────────
  {
    pattern: [/contestaci[oó]n.*(?:demanda.*)?agraria/i, /contestar.*(?:demanda.*agraria|juicio.*agrario)/i, /excepciones.*agrarias/i],
    documentType: 'contestacion_demanda_agraria',
    documentTypeLabel: 'Contestación a la Demanda Agraria',
    matter: 'agrario',
    jurisdiction: 'federal',
    proceduralStage: 'contestacion',
    objective: 'Contestar demanda en juicio agrario oponiendo excepciones',
    requiredInputs: [],
  },
  {
    pattern: [/reconvenci[oó]n.*agraria/i, /demanda.*reconvencional.*agraria/i, /reconvenir.*juicio.*agrario/i],
    documentType: 'reconvencion_agraria',
    documentTypeLabel: 'Reconvención Agraria',
    matter: 'agrario',
    jurisdiction: 'federal',
    proceduralStage: 'reconvencion',
    objective: 'Formular demanda reconvencional en juicio agrario',
    requiredInputs: [],
  },
  {
    pattern: [/alegatos.*agrarios/i, /alegatos.*juicio.*agrario/i, /alegatos.*audiencia.*agraria/i],
    documentType: 'alegatos_agrarios',
    documentTypeLabel: 'Alegatos Agrarios',
    matter: 'agrario',
    jurisdiction: 'federal',
    proceduralStage: 'instruccion',
    objective: 'Formular alegatos en juicio agrario',
    requiredInputs: [],
  },
  {
    pattern: [/cumplimiento.*sentencia.*agraria/i, /ejecuci[oó]n.*sentencia.*agraria/i, /ejecuci[oó]n.*forzosa.*tua/i],
    documentType: 'cumplimiento_sentencia_agraria',
    documentTypeLabel: 'Cumplimiento de Sentencia Agraria',
    matter: 'agrario',
    jurisdiction: 'federal',
    proceduralStage: 'ejecucion',
    objective: 'Promover la ejecución forzosa o cumplimiento de sentencia agraria',
    requiredInputs: [],
  },
  {
    pattern: [/recurso.*agrario/i, /revisi[oó]n.*agraria/i, /recurso.*revisi[oó]n.*tribunal.*superior.*agrario/i, /revisi[oó]n.*tua/i],
    documentType: 'recurso_agrario',
    documentTypeLabel: 'Recurso de Revisión Agraria',
    matter: 'agrario',
    jurisdiction: 'federal',
    proceduralStage: 'recurso',
    objective: 'Interponer recurso de revisión agraria ante el Tribunal Superior Agrario',
    requiredInputs: [],
  },
  {
    pattern: [/demanda.*agraria/i, /juicio.*agrario/i, /tribunal.*unitario.*agrario.*demanda/i, /restituci[oó]n.*tierras.*ejidales/i, /derechos.*parcelarios.*demanda/i],
    documentType: 'demanda_agraria',
    documentTypeLabel: 'Demanda Agraria',
    matter: 'agrario',
    jurisdiction: 'federal',
    proceduralStage: 'inicial',
    objective: 'Promover demanda de juicio agrario ante el Tribunal Unitario Agrario',
    requiredInputs: [],
  },
  // ── MATERIA INMOBILIARIA Y ARRENDAMIENTO ────────────────────────────────────
  {
    pattern: [/promesa.*compraventa.*inmueble/i, /promesa.*compraventa.*(?:casa|terreno|departamento)/i, /contrato.*preparatorio.*inmueble/i],
    documentType: 'promesa_compraventa_inmueble',
    documentTypeLabel: 'Promesa de Compraventa de Inmueble',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'preparatoria',
    objective: 'Celebrar contrato preparatorio de promesa de compraventa de bien inmueble',
    requiredInputs: [],
  },
  {
    pattern: [/compraventa.*inmueble/i, /compraventa.*(?:casa|terreno|departamento|predio)/i, /contrato.*compraventa.*inmobiliaria/i],
    documentType: 'compraventa_inmueble',
    documentTypeLabel: 'Contrato de Compraventa de Inmueble',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'contractual',
    objective: 'Formalizar contrato de compraventa de bien inmueble',
    requiredInputs: [],
  },
  {
    pattern: [/arrendamiento.*inmueble/i, /contrato.*arrendamiento.*(?:casa|departamento|local|bodega)/i, /arrendamiento.*habitacional/i, /arrendamiento.*comercial/i],
    documentType: 'arrendamiento_inmueble',
    documentTypeLabel: 'Contrato de Arrendamiento de Inmueble',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'contractual',
    objective: 'Celebrar contrato de arrendamiento inmobiliario',
    requiredInputs: [],
  },
  {
    pattern: [/convenio.*desocupaci[oó]n/i, /convenio.*transaccional.*desocupaci[oó]n/i, /convenio.*entrega.*inmueble/i],
    documentType: 'convenio_desocupacion',
    documentTypeLabel: 'Convenio de Desocupación de Inmueble',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'transaccional',
    objective: 'Formalizar convenio transaccional de desocupación y entrega de bien inmueble',
    requiredInputs: [],
  },
  {
    pattern: [/reconocimiento.*adeudo.*(?:arrendamiento|rentas?)/i, /convenio.*pago.*rentas.*atrasadas/i, /plan.*pagos.*(?:arrendamiento|rentas?)/i],
    documentType: 'reconocimiento_adeudo_arrendamiento',
    documentTypeLabel: 'Reconocimiento de Adeudo de Arrendamiento',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'contractual',
    objective: 'Celebrar convenio de reconocimiento de adeudo y plan de pagos de rentas',
    requiredInputs: [],
  },
  {
    pattern: [/aviso.*terminaci[oó]n/i, /aviso.*no.*renovaci[oó]n.*arrendamiento/i, /notificaci[oó]n.*desocupaci[oó]n.*voluntaria/i, /aviso.*desocupar/i],
    documentType: 'aviso_terminacion',
    documentTypeLabel: 'Aviso de Terminación de Arrendamiento',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'prejudicial',
    objective: 'Notificar la no renovación de contrato y requerir desocupación',
    requiredInputs: [],
  },
  {
    pattern: [/terminaci[oó]n.*arrendamiento/i, /convenio.*terminaci[oó]n.*renta/i, /finiquito.*arrendamiento/i],
    documentType: 'terminacion_arrendamiento',
    documentTypeLabel: 'Convenio de Terminación de Arrendamiento',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'terminacion',
    objective: 'Formalizar la terminación de contrato de arrendamiento y entrega de posesión',
    requiredInputs: [],
  },
  {
    pattern: [/requerimiento.*pago.*rentas/i, /cobro.*extrajudicial.*rentas/i, /intimaci[oó]n.*pago.*arrendamiento/i, /requerir.*pago.*rentas/i],
    documentType: 'requerimiento_pago_rentas',
    documentTypeLabel: 'Requerimiento de Pago de Rentas',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'prejudicial',
    objective: 'Requerir de pago formal de rentas adeudadas con apercibimiento de rescisión',
    requiredInputs: [],
  },
  {
    pattern: [/demanda.*desocupaci[oó]n/i, /juicio.*especial.*desahucio/i, /controversia.*arrendamiento.*inmobiliario/i, /demanda.*rescisi[oó]n.*arrendamiento/i, /desahucio.*rentas/i],
    documentType: 'demanda_desocupacion',
    documentTypeLabel: 'Demanda de Desocupación y Desahucio',
    matter: 'inmobiliario',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Promover juicio de desahucio y rescisión de contrato de arrendamiento',
    requiredInputs: [],
  },
  // ── MATERIA CORPORATIVA Y SOCIETARIA (15 tipos) ────────────────────────────
  {
    pattern: [/modificaci[oó]n.*estatutos/i, /reforma.*estatut(?:os|aria)/i, /cambio.*objeto.*social/i, /cambio.*denominaci[oó]n.*social/i],
    documentType: 'modificacion_estatutos',
    documentTypeLabel: 'Modificación de Estatutos Sociales',
    matter: 'mercantil',
    jurisdiction: 'notarial_corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar reformas a los estatutos sociales de la sociedad',
    requiredInputs: [],
  },
  {
    pattern: [/constituci[oó]n.*sociedad/i, /creaci[oó]n.*sociedad/i, /constituir.*(?:sa|srl|sas|sociedad)/i, /acta.*constitutiva/i],
    documentType: 'constitucion_sociedad',
    documentTypeLabel: 'Constitución de Sociedad',
    matter: 'mercantil',
    jurisdiction: 'notarial_corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar la constitución y estatutos sociales de una persona moral',
    requiredInputs: [],
  },
  {
    pattern: [/asamblea.*extraordinaria/i, /acta.*asamblea.*extraordinaria/i],
    documentType: 'acta_asamblea_extraordinaria',
    documentTypeLabel: 'Acta de Asamblea Extraordinaria',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Asentar acuerdos de asamblea general extraordinaria de accionistas',
    requiredInputs: [],
  },
  {
    pattern: [/asamblea.*ordinaria/i, /acta.*asamblea.*ordinaria/i, /asamblea.*anual.*accionistas/i],
    documentType: 'acta_asamblea_ordinaria',
    documentTypeLabel: 'Acta de Asamblea Ordinaria',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Asentar acuerdos de asamblea general ordinaria de accionistas',
    requiredInputs: [],
  },
  {
    pattern: [/resoluciones.*unanimidad/i, /resoluciones.*fuera.*asamblea/i, /acuerdos.*un[aá]nimes.*accionistas/i],
    documentType: 'resoluciones_unanimidad',
    documentTypeLabel: 'Resoluciones por Unanimidad fuera de Asamblea',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar resoluciones tomadas por unanimidad de accionistas fuera de asamblea',
    requiredInputs: [],
  },
  {
    pattern: [/acta.*consejo/i, /sesi[oó]n.*consejo.*administraci[oó]n/i, /reuni[oó]n.*consejo.*administraci[oó]n/i],
    documentType: 'acta_consejo',
    documentTypeLabel: 'Acta de Sesión de Consejo de Administración',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Asentar acuerdos tomados en sesión del consejo de administración',
    requiredInputs: [],
  },
  {
    pattern: [/aumento.*capital/i, /incremento.*capital.*social/i],
    documentType: 'aumento_capital',
    documentTypeLabel: 'Aumento de Capital Social',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar resolución y suscripción de aumento de capital social',
    requiredInputs: [],
  },
  {
    pattern: [/reducci[oó]n.*capital/i, /disminuci[oó]n.*capital.*social/i],
    documentType: 'reduccion_capital',
    documentTypeLabel: 'Reducción de Capital Social',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar reducción de capital social con reembolso o absorción de pérdidas',
    requiredInputs: [],
  },
  {
    pattern: [/cesi[oó]n.*partes.*sociales/i, /transmisi[oó]n.*partes.*sociales/i],
    documentType: 'cesion_partes_sociales',
    documentTypeLabel: 'Cesión de Partes Sociales',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar contrato de cesión y transmisión de partes sociales en SRL',
    requiredInputs: [],
  },
  {
    pattern: [/compraventa.*acciones/i, /transmisi[oó]n.*acciones/i, /adquisici[oó]n.*acciones/i],
    documentType: 'compraventa_acciones',
    documentTypeLabel: 'Contrato de Compraventa de Acciones',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar compraventa de acciones representativas del capital social',
    requiredInputs: [],
  },
  {
    pattern: [/revocaci[oó]n.*poder(?:es)?/i, /revocar.*mandato.*corporativo/i, /revocaci[oó]n.*facultades/i],
    documentType: 'revocacion_poder',
    documentTypeLabel: 'Revocación de Poderes',
    matter: 'mercantil',
    jurisdiction: 'notarial_corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar la revocación expresa de poderes y mandato conferidos previamente',
    requiredInputs: [],
  },
  {
    pattern: [/otorgamiento.*poder(?:es)?/i, /conferir.*poder(?:es)?/i, /poderes/i],
    documentType: 'poderes',
    documentTypeLabel: 'Otorgamiento de Poderes',
    matter: 'mercantil',
    jurisdiction: 'notarial_corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar otorgamiento de poderes generales o especiales para pleitos, cobranzas o actos de dominio',
    requiredInputs: [],
  },
  {
    pattern: [/convenio.*accionistas/i, /pacto.*socios/i, /pacto.*parasocial/i, /shareholders.*agreement/i],
    documentType: 'convenio_accionistas',
    documentTypeLabel: 'Convenio de Accionistas',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Celebrar pacto parasocial y convenio de accionistas con derechos de preferencia y sindicación',
    requiredInputs: [],
  },
  {
    pattern: [/acuerdo.*confidencialidad/i, /nda.*corporativo/i],
    documentType: 'acuerdo_confidencialidad',
    documentTypeLabel: 'Acuerdo de Confidencialidad Corporativo',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'corporativo',
    objective: 'Formalizar acuerdo corporativo de confidencialidad y no divulgación de secretos',
    requiredInputs: [],
  },
  {
    pattern: [/carta.*intenci[oó]n/i, /loi/i, /letter.*intent/i],
    documentType: 'carta_intencion',
    documentTypeLabel: 'Carta de Intención',
    matter: 'mercantil',
    jurisdiction: 'corporativo',
    proceduralStage: 'precontractual',
    objective: 'Fijar bases de entendimiento preliminar y calendario de debida diligencia',
    requiredInputs: [],
  },

  // ── MATERIA CONTRACTUAL (17 tipos) ─────────────────────────────────────────
  {
    pattern: [/convenio.*reconocimiento.*adeudo/i, /reconocimiento.*adeudo.*convenio/i, /reestructuraci[oó]n.*deuda.*convenio/i],
    documentType: 'convenio_reconocimiento_adeudo',
    documentTypeLabel: 'Convenio de Reconocimiento de Adeudo',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Formalizar reconocimiento expreso de adeudo líquido con calendario de pago',
    requiredInputs: [],
  },
  {
    pattern: [/convenio.*transaccional(?!.*desocupaci)/i, /transacci[oó]n.*extrajudicial/i, /finiquito.*transaccional/i],
    documentType: 'convenio_transaccional',
    documentTypeLabel: 'Convenio Transaccional',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Celebrar transacción para prevenir o terminar litigio mediante recíprocas concesiones',
    requiredInputs: [],
  },
  {
    pattern: [/convenio.*terminaci[oó]n(?!.*arrendamiento)/i, /rescisi[oó]n.*mutuo.*acuerdo/i, /terminaci[oó]n.*anticipada.*contrato/i],
    documentType: 'convenio_terminacion',
    documentTypeLabel: 'Convenio de Terminación de Contrato',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Dar por terminado contrato previo de común acuerdo otorgando finiquito mutuo',
    requiredInputs: [],
  },
  {
    pattern: [/convenio.*modificatorio/i, /adenda.*contrato/i, /adendum.*contrato/i, /pr[oó]rroga.*contrato/i],
    documentType: 'convenio_modificatorio',
    documentTypeLabel: 'Convenio Modificatorio (Addendum)',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Modificar estipulaciones o plazos de contrato vigente sin novar la obligación principal',
    requiredInputs: [],
  },
  {
    pattern: [/memorando.*entendimiento/i, /mou.*comercial/i, /memorandum.*understanding/i],
    documentType: 'memorando_entendimiento',
    documentTypeLabel: 'Memorando de Entendimiento (MOU)',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'precontractual',
    objective: 'Formalizar entendimiento y bases preliminares de acuerdo entre las partes',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*confidencialidad/i, /acuerdo.*no.*divulgaci[oó]n/i, /nda.*contractual/i],
    documentType: 'contrato_confidencialidad',
    documentTypeLabel: 'Contrato de Confidencialidad (NDA)',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Obligar a las partes a guardar reserva de información técnica o comercial',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*licencia(?!.*(?:marca|autor|obra|indautor))/i, /licencia.*uso.*software/i, /licencia.*tecnolog[ií]a/i],
    documentType: 'contrato_licencia',
    documentTypeLabel: 'Contrato de Licencia de Software o Tecnología',
    matter: 'contractual',
    jurisdiction: 'mercantil',
    proceduralStage: 'contractual',
    objective: 'Conceder licencia de explotación o uso de software o tecnología',
    requiredInputs: [],
  },
  {
    pattern: [/obra.*precio.*alzado/i, /contrato.*construcci[oó]n/i, /contrato.*obra(?!.*(?:autor|intelectual|literaria|art[ií]stica|licencia))/i],
    documentType: 'contrato_obra',
    documentTypeLabel: 'Contrato de Obra a Precio Alzado',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Encargar ejecución de obra bajo riesgo del contratista a precio alzado',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*mutuo/i, /mutuo.*inter[eé]s/i, /pr[eé]stamo.*dinero.*mutuo/i],
    documentType: 'contrato_mutuo',
    documentTypeLabel: 'Contrato de Mutuo',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Transferir propiedad de dinero con obligación de restituir e intereses pactados',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*comodato/i, /pr[eé]stamo.*uso.*gratuito/i],
    documentType: 'contrato_comodato',
    documentTypeLabel: 'Contrato de Comodato',
    matter: 'contractual',
    jurisdiction: 'civil',
    proceduralStage: 'contractual',
    objective: 'Conceder uso gratuito temporal de bien no fungible',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*mandato/i, /mandato.*civil/i],
    documentType: 'contrato_mandato',
    documentTypeLabel: 'Contrato de Mandato',
    matter: 'contractual',
    jurisdiction: 'civil',
    proceduralStage: 'contractual',
    objective: 'Encomendar realización de actos jurídicos por cuenta del mandante',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*comisi[oó]n/i, /comisi[oó]n.*mercantil/i],
    documentType: 'contrato_comision',
    documentTypeLabel: 'Contrato de Comisión Mercantil',
    matter: 'contractual',
    jurisdiction: 'mercantil',
    proceduralStage: 'contractual',
    objective: 'Encomendar actos de comercio a cambio de comisión mercantil',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*distribuci[oó]n/i, /distribuidor.*autorizado/i],
    documentType: 'contrato_distribucion',
    documentTypeLabel: 'Contrato de Distribución Mercantil',
    matter: 'contractual',
    jurisdiction: 'mercantil',
    proceduralStage: 'contractual',
    objective: 'Conceder distribución de productos en territorio asignado',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*suministro/i, /suministro.*mercanc[ií]as/i, /suministro.*bienes/i],
    documentType: 'contrato_suministro',
    documentTypeLabel: 'Contrato de Suministro',
    matter: 'contractual',
    jurisdiction: 'mercantil',
    proceduralStage: 'contractual',
    objective: 'Asegurar la provisión continua y periódica de bienes o insumos',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*prestaci[oó]n.*servicios/i, /servicios.*profesionales/i, /honorarios.*profesionales/i],
    documentType: 'contrato_prestacion_servicios',
    documentTypeLabel: 'Contrato de Prestación de Servicios',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Pactar la ejecución de servicios técnicos o profesionales independientes',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*arrendamiento(?!.*inmueble)/i, /arrendamiento.*muebles/i, /arrendamiento.*maquinaria/i],
    documentType: 'contrato_arrendamiento',
    documentTypeLabel: 'Contrato de Arrendamiento',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Conceder uso o goce temporal de bienes a cambio de renta convenida',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*compraventa(?!.*(?:inmueble|casa|terreno|acciones))/i, /compraventa.*muebles/i, /compraventa.*mercantil/i],
    documentType: 'contrato_compraventa',
    documentTypeLabel: 'Contrato de Compraventa',
    matter: 'contractual',
    jurisdiction: 'civil_mercantil',
    proceduralStage: 'contractual',
    objective: 'Transmitir dominio de bienes muebles a cambio de precio cierto en dinero',
    requiredInputs: [],
  },

  // ── MATERIA PROPIEDAD INTELECTUAL (11 tipos) ─────────────────────────────
  {
    pattern: [/contestaci[oó]n.*impedimento/i, /desahogo.*oficio.*requisitos.*impi/i, /respuesta.*impedimento.*legal.*impi/i],
    documentType: 'contestacion_impedimento',
    documentTypeLabel: 'Contestación a Oficio de Impedimento Legal del IMPI',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'tramite',
    objective: 'Desahogar oficio de requisitos y rebatir objeciones o anterioridades del IMPI',
    requiredInputs: [],
  },
  {
    pattern: [/oposici[oó]n.*marca/i, /escrito.*oposici[oó]n.*impi/i, /oponerse.*registro.*marca/i],
    documentType: 'oposicion_marca',
    documentTypeLabel: 'Oposición a Solicitud de Registro de Marca',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'oposicion',
    objective: 'Formular oposición contra solicitud de marca publicada en la Gaceta del IMPI',
    requiredInputs: [],
  },
  {
    pattern: [/nulidad.*registro.*(?:marca|patente)/i, /demanda.*nulidad.*impi/i, /declaraci[oó]n.*administrativa.*nulidad/i],
    documentType: 'nulidad_registro',
    documentTypeLabel: 'Solicitud de Declaración Administrativa de Nulidad',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'contencioso',
    objective: 'Demandarle al IMPI la declaración administrativa de nulidad de registro marcario',
    requiredInputs: [],
  },
  {
    pattern: [/caducidad.*registro/i, /caducidad.*marca/i, /falta.*uso.*marca.*caducidad/i],
    documentType: 'caducidad_registro',
    documentTypeLabel: 'Solicitud de Declaración Administrativa de Caducidad',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'contencioso',
    objective: 'Demandarle al IMPI la caducidad de registro marcario por falta de uso',
    requiredInputs: [],
  },
  {
    pattern: [
      /infracci[oó]n.*propiedad.*industrial/i,
      /infracci[oó]n.*administrativa.*impi/i,
      /denuncia.*infracci[oó]n.*marcaria/i,
      /(?:declaraci[oó]n.*)?administrativa.*infracci[oó]n/i,
      /infracci[oó]n.*(?:ante\s+)?impi/i,
    ],
    documentType: 'infraccion_propiedad_industrial',
    documentTypeLabel: 'Declaración Administrativa de Infracción ante IMPI',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'contencioso',
    objective: 'Denunciar infracción administrativa ante el IMPI por uso indebido de marca o patente',
    requiredInputs: [],
  },
  {
    pattern: [
      /recurso.*propiedad.*intelectual/i,
      /recurso.*revisi[oó]n.*impi/i,
      /impugnaci[oó]n.*resoluci[oó]n.*impi/i,
      /revisi[oó]n.*(?:en\s+sede\s+administrativa.*)?(?:ante|del)\s+impi/i,
    ],
    documentType: 'recurso_propiedad_intelectual',
    documentTypeLabel: 'Recurso de Revisión ante el IMPI',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'recurso',
    objective: 'Interponer recurso de revisión en sede administrativa contra resolución del IMPI',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*registro.*marca/i, /registrar.*marca.*impi/i, /solicitud.*impi.*marca/i],
    documentType: 'solicitud_registro_marca',
    documentTypeLabel: 'Solicitud de Registro de Marca',
    matter: 'propiedad_intelectual',
    jurisdiction: 'federal_impi',
    proceduralStage: 'tramite',
    objective: 'Solicitar registro formal de marca o signo distintivo ante el IMPI',
    requiredInputs: [],
  },
  {
    pattern: [/contrato.*licencia.*marca/i, /licencia.*uso.*marca/i, /licencia.*signos.*distintivos/i],
    documentType: 'contrato_licencia_marca',
    documentTypeLabel: 'Contrato de Licencia de Marca',
    matter: 'propiedad_intelectual',
    jurisdiction: 'mercantil_pi',
    proceduralStage: 'contractual',
    objective: 'Celebrar contrato de licencia de explotación de marca con estándares de calidad',
    requiredInputs: [],
  },
  {
    pattern: [/cesi[oó]n.*derechos.*marca/i, /transmisi[oó]n.*derechos.*marca/i, /cesi[oó]n.*marca.*impi/i],
    documentType: 'cesion_derechos_marca',
    documentTypeLabel: 'Contrato de Cesión de Derechos de Marca',
    matter: 'propiedad_intelectual',
    jurisdiction: 'mercantil_pi',
    proceduralStage: 'contractual',
    objective: 'Transmitir a título definitivo los derechos patrimoniales sobre registro de marca',
    requiredInputs: [],
  },
  {
    pattern: [/licencia.*derechos.*autor/i, /licencia.*obra.*indautor/i, /autorizaci[oó]n.*uso.*obra/i],
    documentType: 'licencia_derechos_autor',
    documentTypeLabel: 'Contrato de Licencia de Derechos de Autor',
    matter: 'propiedad_intelectual',
    jurisdiction: 'derechos_autor',
    proceduralStage: 'contractual',
    objective: 'Autorizar explotación temporal de obra preservando derechos morales de autor',
    requiredInputs: [],
  },
  {
    pattern: [/cesi[oó]n.*derechos.*autor/i, /transmisi[oó]n.*derechos.*patrimoniales.*autor/i, /cesi[oó]n.*patrimonial.*indautor/i],
    documentType: 'cesion_derechos_autor',
    documentTypeLabel: 'Contrato de Cesión de Derechos de Autor',
    matter: 'propiedad_intelectual',
    jurisdiction: 'derechos_autor',
    proceduralStage: 'contractual',
    objective: 'Transmitir derechos patrimoniales de explotación sobre obra artística o literaria',
    requiredInputs: [],
  },
  ...CATALOGED_DEMAND_SUBTYPE_RULES,
  {
    pattern: [demandWithoutSubtypePattern('civil')],
    documentType: NEEDS_DOCUMENT_TYPE_SELECTION,
    documentTypeLabel: 'Seleccionar subtipo de demanda civil',
    matter: 'civil',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Requiere seleccionar el subtipo de demanda civil antes de generar',
    requiredInputs: [{
      id: 'document_type_subtype',
      label: 'Subtipo de demanda civil',
      description: 'Seleccione el subtipo canónico de demanda civil.',
      type: 'select',
      required: true,
    }],
  },
  {
    pattern: [demandWithoutSubtypePattern('mercantil')],
    documentType: NEEDS_DOCUMENT_TYPE_SELECTION,
    documentTypeLabel: 'Seleccionar subtipo de demanda mercantil',
    matter: 'mercantil',
    jurisdiction: 'local',
    proceduralStage: 'inicial',
    objective: 'Requiere seleccionar el subtipo de demanda mercantil antes de generar',
    requiredInputs: [{
      id: 'document_type_subtype',
      label: 'Subtipo de demanda mercantil',
      description: 'Seleccione el subtipo canónico de demanda mercantil.',
      type: 'select',
      required: true,
    }],
  },
  {
    pattern: [/contestaci[oó]n/i, /contestar/i],
    documentType: 'contestacion_demanda',
    documentTypeLabel: 'Contestación de Demanda',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'instruccion',
    objective: 'Dar contestación a una demanda',
    requiredInputs: []
  },
  {
    pattern: [/escrito.*agravios/i, /agravios/i],
    documentType: 'escrito_agravios',
    documentTypeLabel: 'Escrito de Agravios',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'recurso',
    objective: 'Expresar agravios en recurso de apelación',
    requiredInputs: []
  },
  {
    pattern: [/recurso.*resoluci[oó]n/i, /impugnar.*resoluci[oó]n/i, /recurso\s+administrativo/i],
    documentType: 'recurso_administrativo',
    documentTypeLabel: 'Recurso Administrativo',
    matter: 'administrativo',
    jurisdiction: 'administrativo',
    proceduralStage: 'impugnacion',
    objective: 'Impugnar resolución ante autoridad administrativa',
    requiredInputs: []
  },
  {
    pattern: [/cumplimiento.*sentencia/i],
    documentType: 'escrito_cumplimiento_sentencia',
    documentTypeLabel: 'Escrito sobre Cumplimiento de Sentencia',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'ejecucion',
    objective: 'Manifestar cumplimiento o incumplimiento de sentencia',
    requiredInputs: []
  },
  {
    pattern: [/incidente/i],
    documentType: 'incidente_procesal',
    documentTypeLabel: 'Incidente Procesal',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'incidental',
    objective: 'Resolver cuestión accesoria al juicio',
    requiredInputs: []
  },
  {
    pattern: [/r[eé]plica/i],
    documentType: 'replica',
    documentTypeLabel: 'Escrito de Réplica',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'instruccion',
    objective: 'Contestar excepciones y defensas',
    requiredInputs: []
  },
  {
    pattern: [/d[uú]plica/i],
    documentType: 'duplica',
    documentTypeLabel: 'Escrito de Dúplica',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'instruccion',
    objective: 'Contestar a la réplica',
    requiredInputs: []
  },
  // ── MATERIA TRÁMITES GENERALES DE JUZGADO (25 tipos) ───────────────────────
  {
    pattern: [/promoci[oó]n.*simple/i, /escrito.*tr[aá]mite.*general/i, /promoci[oó]n.*de.*tr[aá]mite/i],
    documentType: 'promocion_simple',
    documentTypeLabel: 'Promoción Simple de Trámite',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Formular gestión o promoción procesal de trámite ordinario',
    requiredInputs: [],
  },
  {
    pattern: [/desahog.*prevenci[oó]n/i, /aclaraci[oó]n.*demanda/i, /desahogo.*requerimiento.*prevenci[oó]n/i],
    documentType: 'desahogo_prevencion',
    documentTypeLabel: 'Desahogo de Prevención Judicial',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'subsanacion',
    objective: 'Desahogar prevención y subsanar aclaraciones requeridas por el tribunal',
    requiredInputs: [],
  },
  {
    pattern: [/cumplimiento.*requerimiento/i, /cumplir.*requerimiento.*judicial/i, /atenci[oó]n.*mandamiento.*judicial/i],
    documentType: 'cumplimiento_requerimiento',
    documentTypeLabel: 'Cumplimiento de Requerimiento Judicial',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Dar cabal cumplimiento a un requerimiento formulado por el juez',
    requiredInputs: [],
  },
  {
    pattern: [/cumplimiento.*prevenci[oó]n/i, /subsanaci[oó]n.*prevenci[oó]n/i],
    documentType: 'cumplimiento_prevencion',
    documentTypeLabel: 'Cumplimiento y Subsanación de Prevención',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'subsanacion',
    objective: 'Acreditar el cumplimiento y subsanación de la prevención decretada',
    requiredInputs: [],
  },
  {
    pattern: [/escrito.*manifestaciones/i, /desahogo.*vista(?!.*(?:amparo|laboral|fiscal))/i, /manifestaciones.*autos/i],
    documentType: 'manifestaciones',
    documentTypeLabel: 'Escrito de Manifestaciones',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Hacer valer consideraciones fácticas y jurídicas respecto de una actuación',
    requiredInputs: [],
  },
  {
    pattern: [/escrito.*comparecencia/i, /apersonamiento.*autos/i, /comparecer.*juicio/i],
    documentType: 'comparecencia',
    documentTypeLabel: 'Escrito de Comparecencia y Apersonamiento',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Comparecer formalmente a autos y señalar domicilio y autorizados',
    requiredInputs: [],
  },
  {
    pattern: [/ratificaci[oó]n.*(?:escrito|firma|contenido)/i, /escrito.*ratificaci[oó]n/i, /ratificar.*convenio.*firma/i],
    documentType: 'ratificacion',
    documentTypeLabel: 'Escrito de Ratificación de Contenido y Firma',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Ratificar expresamente el contenido y firma de escrito o convenio',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*copias.*simples/i, /copias.*simples.*autos/i, /solicitud.*copias(?!.*certificadas)/i],
    documentType: 'solicitud_copias',
    documentTypeLabel: 'Solicitud de Copias Simples',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar expedición de copias simples de constancias del expediente',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*copias.*certificadas/i, /copias.*certificadas.*expediente/i, /expedici[oó]n.*copias.*certificadas/i],
    documentType: 'solicitud_copias_certificadas',
    documentTypeLabel: 'Solicitud de Copias Certificadas',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar expedición de copias certificadas por secretaría a costa del promovente',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*acceso.*expediente/i, /consulta.*expediente.*electr[oó]nico/i, /acceso.*expediente.*virtual/i],
    documentType: 'solicitud_acceso_expediente',
    documentTypeLabel: 'Solicitud de Acceso y Consulta al Expediente',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar acceso físico o electrónico al expediente judicial',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*certificaci[oó]n.*t[eé]rminos/i, /certificaci[oó]n.*secretarial/i, /solicitud.*certificaci[oó]n(?!.*copias)/i],
    documentType: 'solicitud_certificacion',
    documentTypeLabel: 'Solicitud de Certificación Secretarial',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Pedir al Secretario de Acuerdos certificación de términos o estado procesal',
    requiredInputs: [],
  },
  {
    pattern: [/autorizaci[oó]n.*abogados/i, /designaci[oó]n.*abogados.*patronos/i, /autorizados.*para.*o[ií]r.*notificaciones/i, /nombramiento.*abogados/i],
    documentType: 'autorizacion_abogados',
    documentTypeLabel: 'Autorización y Designación de Abogados',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Designar abogados patronos y pasantes autorizados en términos de ley',
    requiredInputs: [],
  },
  {
    pattern: [/revocaci[oó]n.*(?:abogados|autorizados|nombramientos)/i, /revocar.*abogados.*patronos/i],
    documentType: 'revocacion_autorizados',
    documentTypeLabel: 'Revocación de Abogados y Autorizados',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Revocar profesionistas y autorizados anteriormente señalados en autos',
    requiredInputs: [],
  },
  {
    pattern: [/cambio.*domicilio.*procesal/i, /nuevo.*domicilio.*notificaciones/i, /se[ñn]alamiento.*nuevo.*domicilio/i],
    documentType: 'cambio_domicilio_procesal',
    documentTypeLabel: 'Cambio de Domicilio Procesal',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Señalar nuevo domicilio procesal dentro de la jurisdicción del juzgado',
    requiredInputs: [],
  },
  {
    pattern: [/se[ñn]alamiento.*correo/i, /correo.*electr[oó]nico.*notificaciones/i, /autorizaci[oó]n.*notificaciones.*electr[oó]nicas/i],
    documentType: 'senalamiento_correo',
    documentTypeLabel: 'Señalamiento de Correo para Notificaciones Electrónicas',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Señalar correo electrónico y usuario del sistema de notificación digital',
    requiredInputs: [],
  },
  {
    pattern: [/impulso.*procesal/i, /solicitud.*avance.*procesal/i, /pase.*siguiente.*etapa/i, /continuaci[oó]n.*juicio.*impulso/i],
    documentType: 'impulso_procesal',
    documentTypeLabel: 'Solicitud de Impulso Procesal',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar al tribunal decrete el avance procesal a la siguiente fase del juicio',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*acumulaci[oó]n.*autos/i, /acumulaci[oó]n.*expedientes/i, /acumulaci[oó]n.*juicios.*conex/i],
    documentType: 'solicitud_acumulacion',
    documentTypeLabel: 'Solicitud de Acumulación de Expedientes',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'incidental',
    objective: 'Solicitar la acumulación de juicios conexos para resolverse en una sola sentencia',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*desarchivo/i, /desarchivo.*expediente/i, /devoluci[oó]n.*archivo.*judicial/i, /solicitar.*autos.*del.*archivo/i, /desarchivo/i],
    documentType: 'solicitud_desarchivo',
    documentTypeLabel: 'Solicitud de Desarchivo de Expediente',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar la devolución del expediente del Archivo Judicial al juzgado',
    requiredInputs: [],
  },
  {
    pattern: [/solicitud.*archivo.*definitivo/i, /mandar.*archivar.*expediente/i, /archivo.*autos.*conclusi[oó]n/i, /solicitud.*(?<!des)archivo/i],
    documentType: 'solicitud_archivo',
    documentTypeLabel: 'Solicitud de Archivo Definitivo',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'conclusion',
    objective: 'Solicitar la remisión del expediente al archivo judicial por estar concluido',
    requiredInputs: [],
  },
  {
    pattern: [/escrito.*desistimiento/i, /desistimiento.*demanda/i, /desistimiento.*acci[oó]n/i, /desistir.*instancia/i],
    documentType: 'desistimiento',
    documentTypeLabel: 'Escrito de Desistimiento',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'conclusion',
    objective: 'Desistirse formalmente de la demanda, de la instancia o de la acción intentada',
    requiredInputs: [],
  },
  {
    pattern: [/escrito.*allanamiento/i, /allanamiento.*demanda/i, /allanarse.*pretensiones/i],
    documentType: 'allanamiento',
    documentTypeLabel: 'Escrito de Allanamiento a la Demanda',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'contestacion',
    objective: 'Allanarse incondicionalmente a las pretensiones de la demanda',
    requiredInputs: [],
  },
  {
    pattern: [/presentaci[oó]n.*convenio.*judicial/i, /ratificaci[oó]n.*convenio.*judicial/i, /convenio.*transacci[oó]n.*judicial/i, /convenio.*judicial/i],
    documentType: 'convenio_judicial',
    documentTypeLabel: 'Convenio Judicial de Transacción',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'conclusion',
    objective: 'Presentar y solicitar aprobación y elevación a cosa juzgada de convenio',
    requiredInputs: [],
  },
  {
    pattern: [/aclaraci[oó]n.*auto/i, /aclaraci[oó]n.*prove[ií]do/i, /solicitud.*aclaraci[oó]n.*acuerdo/i],
    documentType: 'aclaracion',
    documentTypeLabel: 'Solicitud de Aclaración de Auto o Proveído',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Pedir la aclaración de contradicciones o puntos obscuros en un auto judicial',
    requiredInputs: [],
  },
  {
    pattern: [/correcci[oó]n.*error.*material/i, /correcci[oó]n.*error.*mecanogr[aá]fico/i, /rectificaci[oó]n.*error.*num[eé]rico/i, /correcci[oó]n.*error.*actuaci[oó]n/i],
    documentType: 'correccion_error',
    documentTypeLabel: 'Solicitud de Corrección de Error Material',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar la corrección de errores materiales o numéricos en actuaciones',
    requiredInputs: [],
  },
  {
    pattern: [/devoluci[oó]n.*documentos.*originales/i, /solicitud.*devoluci[oó]n.*documentos/i, /entrega.*documentos.*originales/i],
    documentType: 'solicitud_devolucion_documentos',
    documentTypeLabel: 'Solicitud de Devolución de Documentos Originales',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'tramite',
    objective: 'Solicitar devolución de documentos originales dejando copia certificada',
    requiredInputs: [],
  },
  {
    pattern: [/demanda/i],
    documentType: 'demanda',
    documentTypeLabel: 'Demanda Inicial',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'inicial',
    objective: 'Iniciar procedimiento judicial',
    requiredInputs: []
  },
  {
    pattern: [/escrito.*libre/i, /promoci[oó]n/i],
    documentType: 'escrito_libre',
    documentTypeLabel: 'Escrito Libre',
    matter: 'general',
    jurisdiction: 'general',
    proceduralStage: 'cualquiera',
    objective: 'Realizar peticiones diversas',
    requiredInputs: []
  }
];

const FALLBACK_CLASSIFICATION: ClassificationResult = {
  documentType: 'escrito_libre',
  documentTypeLabel: 'Escrito Libre / Promoción',
  matter: 'general',
  jurisdiction: 'general',
  proceduralStage: 'cualquiera',
  objective: 'Solicitud libre al órgano jurisdiccional',
  requiredInputs: [],
  confidence: 0,
  isDynamic: true
};

export function classifyIntent(userText: string): ClassificationResult {
  const text = userText.toLowerCase();
  
  for (const rule of DOC_TYPE_RULES) {
    for (const pattern of rule.pattern) {
      if (pattern.test(text)) {
        return {
          documentType: rule.documentType,
          documentTypeLabel: rule.documentTypeLabel,
          matter: rule.matter,
          jurisdiction: rule.jurisdiction,
          proceduralStage: rule.proceduralStage,
          authority: rule.authority,
          objective: rule.objective,
          requiredInputs: rule.requiredInputs,
          confidence: 0.8,
          isDynamic: false
        };
      }
    }
  }
  
  return { ...FALLBACK_CLASSIFICATION };
}

export function mergeWithAiClassification(base: ClassificationResult, aiClass: Partial<ClassificationResult>): ClassificationResult {
  return { ...base, ...aiClass, confidence: (base.confidence || 0) + 0.1 };
}
