/**
 * Contrato único para los tipos de documentos fuente que intervienen en
 * compatibilidad fuente -> salida.
 *
 * Los valores externos pueden traer acentos, espacios o guiones. La
 * normalización siempre devuelve un valor canónico conocido o `undefined`;
 * nunca inventa un tipo nuevo a partir de una cadena desconocida.
 */

export const SOURCE_TYPE_UNKNOWN = 'SOURCE_TYPE_UNKNOWN' as const;
export const UNKNOWN_SOURCE_DOCUMENT_TYPE = 'DOCUMENTO_JURIDICO_NO_CLASIFICADO' as const;
export const NO_SOURCE_DOCUMENT = 'NO_SOURCE_DOCUMENT' as const;

export const SOURCE_DOCUMENT_TYPES = [
  'DEMANDA',
  'DEMANDA_CIVIL',
  'DEMANDA_MERCANTIL',
  'DEMANDA_LABORAL',
  'DEMANDA_AMPARO',
  'DEMANDA_AMPARO_DIRECTO',
  'INFORME_JUSTIFICADO',
  'INFORME_PREVIO',
  'ESCRITO_INICIAL_CIVIL',
  'ESCRITO_INICIAL_MERCANTIL',
  'ESCRITO_INICIAL_LABORAL',
  'PAGARE',
  'TITULO_CREDITO',
  'CONVENIO_MERCANTIL',
  'DOCUMENTO_MERCANTIL_BASE',
  'REQUERIMIENTO_MERCANTIL',
  'ESTADO_CUENTA_MERCANTIL',
  'COMUNICACION_MERCANTIL',
  'PAGO_MERCANTIL',
  'DOCUMENTO_MERCANTIL_AUXILIAR',
  'CONTRATO_CIVIL',
  'CONVENIO_CIVIL',
  'REQUERIMIENTO_CIVIL',
  'COMUNICACION_CIVIL',
  'PRUEBA_DOCUMENTAL_CIVIL',
  'DOCUMENTO_CIVIL_AUXILIAR',
  'SENTENCIA_O_RESOLUCION',
  'SENTENCIA_AMPARO',
  'SENTENCIA_AMPARO_DIRECTO',
  'LAUDO',
  'ACUERDO',
  'ACTO_DE_AUTORIDAD',
  'RESOLUCION_ADMINISTRATIVA',
  'CONTESTACION_DEMANDA',
  'CONTESTACION_DEMANDA_CIVIL',
  'CONTESTACION_DEMANDA_MERCANTIL',
  'RECONVENCION_CIVIL',
  'RECONVENCION_MERCANTIL',
  'EXCEPCIONES_DEFENSAS_MERCANTIL',
  'REPLICA',
  'DUPLICA',
  'RECURSO',
] as const;

export type SourceDocumentType = (typeof SOURCE_DOCUMENT_TYPES)[number];
export type InferredSourceDocumentType = SourceDocumentType | typeof UNKNOWN_SOURCE_DOCUMENT_TYPE;
export type SourceDocumentTypeValue = InferredSourceDocumentType | typeof NO_SOURCE_DOCUMENT;

const SOURCE_DOCUMENT_TYPE_ALIASES: Readonly<Record<string, SourceDocumentType>> = {
  DEMANDA: 'DEMANDA',
  DEMANDA_CIVIL: 'DEMANDA_CIVIL',
  DEMANDA_MERCANTIL: 'DEMANDA_MERCANTIL',
  DEMANDA_LABORAL: 'DEMANDA_LABORAL',
  DEMANDA_AMPARO: 'DEMANDA_AMPARO',
  DEMANDA_DE_AMPARO: 'DEMANDA_AMPARO',
  DEMANDA_AMPARO_DIRECTO: 'DEMANDA_AMPARO_DIRECTO',
  DEMANDA_DE_AMPARO_DIRECTO: 'DEMANDA_AMPARO_DIRECTO',
  INFORME_JUSTIFICADO: 'INFORME_JUSTIFICADO',
  INFORME_PREVIO: 'INFORME_PREVIO',
  ESCRITO_INICIAL_CIVIL: 'ESCRITO_INICIAL_CIVIL',
  ESCRITO_INICIAL_MERCANTIL: 'ESCRITO_INICIAL_MERCANTIL',
  ESCRITO_INICIAL_LABORAL: 'ESCRITO_INICIAL_LABORAL',
  PAGARE: 'PAGARE',
  PAGARÉ: 'PAGARE',
  PAGARE_MERCANTIL: 'PAGARE',
  TITULO_CREDITO: 'TITULO_CREDITO',
  TITULO_DE_CREDITO: 'TITULO_CREDITO',
  CONVENIO_MERCANTIL: 'CONVENIO_MERCANTIL',
  DOCUMENTO_MERCANTIL_BASE: 'DOCUMENTO_MERCANTIL_BASE',
  REQUERIMIENTO_MERCANTIL: 'REQUERIMIENTO_MERCANTIL',
  ESTADO_CUENTA_MERCANTIL: 'ESTADO_CUENTA_MERCANTIL',
  COMUNICACION_MERCANTIL: 'COMUNICACION_MERCANTIL',
  PAGO_MERCANTIL: 'PAGO_MERCANTIL',
  DOCUMENTO_MERCANTIL_AUXILIAR: 'DOCUMENTO_MERCANTIL_AUXILIAR',
  CONTRATO_CIVIL: 'CONTRATO_CIVIL',
  CONTRATO: 'CONTRATO_CIVIL',
  CONVENIO_CIVIL: 'CONVENIO_CIVIL',
  CONVENIO: 'CONVENIO_CIVIL',
  REQUERIMIENTO_CIVIL: 'REQUERIMIENTO_CIVIL',
  REQUERIMIENTO: 'REQUERIMIENTO_CIVIL',
  COMUNICACION_CIVIL: 'COMUNICACION_CIVIL',
  COMUNICACION: 'COMUNICACION_CIVIL',
  PRUEBA_DOCUMENTAL_CIVIL: 'PRUEBA_DOCUMENTAL_CIVIL',
  DOCUMENTO_CIVIL_AUXILIAR: 'DOCUMENTO_CIVIL_AUXILIAR',
  ESCRITO_INICIAL: 'DEMANDA',
  SENTENCIA: 'SENTENCIA_O_RESOLUCION',
  EJECUTORIA: 'SENTENCIA_O_RESOLUCION',
  RESOLUCION: 'SENTENCIA_O_RESOLUCION',
  RESOLUCION_DEFINITIVA: 'SENTENCIA_O_RESOLUCION',
  SENTENCIA_DEFINITIVA: 'SENTENCIA_O_RESOLUCION',
  SENTENCIA_O_RESOLUCION: 'SENTENCIA_O_RESOLUCION',
  SENTENCIA_AMPARO: 'SENTENCIA_AMPARO',
  SENTENCIA_DE_AMPARO: 'SENTENCIA_AMPARO',
  SENTENCIA_AMPARO_DIRECTO: 'SENTENCIA_AMPARO_DIRECTO',
  SENTENCIA_DE_AMPARO_DIRECTO: 'SENTENCIA_AMPARO_DIRECTO',
  LAUDO: 'LAUDO',
  LAUDO_LABORAL: 'LAUDO',
  LAUDO_ARBITRAL: 'LAUDO',
  ACUERDO: 'ACUERDO',
  ACTO_DE_AUTORIDAD: 'ACTO_DE_AUTORIDAD',
  RESOLUCION_ADMINISTRATIVA: 'RESOLUCION_ADMINISTRATIVA',
  CONTESTACION: 'CONTESTACION_DEMANDA',
  CONTESTACION_DEMANDA: 'CONTESTACION_DEMANDA',
  CONTESTACION_DE_LA_DEMANDA: 'CONTESTACION_DEMANDA',
  CONTESTACION_DEMANDA_CIVIL: 'CONTESTACION_DEMANDA_CIVIL',
  CONTESTACION_DEMANDA_MERCANTIL: 'CONTESTACION_DEMANDA_MERCANTIL',
  RECONVENCION_CIVIL: 'RECONVENCION_CIVIL',
  RECONVENCION_MERCANTIL: 'RECONVENCION_MERCANTIL',
  EXCEPCIONES_DEFENSAS_MERCANTIL: 'EXCEPCIONES_DEFENSAS_MERCANTIL',
  REPLICA: 'REPLICA',
  DUPLICA: 'DUPLICA',
  RECURSO: 'RECURSO',
};

function normalizeToken(value: string): string {
  return value
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export function normalizeSourceDocumentType(value: unknown): SourceDocumentType | undefined {
  if (typeof value !== 'string' || !value.trim()) return undefined;
  return SOURCE_DOCUMENT_TYPE_ALIASES[normalizeToken(value)];
}

export function isSourceDocumentType(value: unknown): value is SourceDocumentType {
  return normalizeSourceDocumentType(value) !== undefined;
}

export function sourceDocumentMatter(type: SourceDocumentType): string {
  if (type === 'PAGARE' || type === 'TITULO_CREDITO' || type === 'CONVENIO_MERCANTIL'
    || type === 'DOCUMENTO_MERCANTIL_BASE' || type === 'REQUERIMIENTO_MERCANTIL'
    || type === 'ESTADO_CUENTA_MERCANTIL' || type === 'COMUNICACION_MERCANTIL'
    || type === 'PAGO_MERCANTIL' || type === 'DOCUMENTO_MERCANTIL_AUXILIAR') return 'MERCANTIL';
  if (type.includes('MERCANTIL')) return 'MERCANTIL';
  if (type.includes('CIVIL')) return 'CIVIL';
  if (type.includes('LABORAL') || type === 'LAUDO') return 'LABORAL';
  if (type.includes('ADMINISTRATIVA')) return 'ADMINISTRATIVA';
  if (type.includes('AMPARO')) return 'AMPARO';
  if (type === 'INFORME_JUSTIFICADO' || type === 'INFORME_PREVIO') return 'AMPARO';
  return 'NO_IDENTIFICADA';
}
