import { ProfessionalTemplate } from './templateTypes';

const commonDisclaimer = "Este documento es una base de trabajo generada automáticamente. Requiere revisión profesional obligatoria antes de presentarse ante cualquier autoridad. No constituye asesoría jurídica.";
const pendingLegalBasis =
  '[PENDIENTE: verificar fundamento normativo aplicable según materia, jurisdicción y vía]';
const pendingApplicableLaws = [
  '[PENDIENTE: verificar legislación aplicable según materia y jurisdicción]',
];

export const templates: ProfessionalTemplate[] = [
  {
    id: 'amparo-indirecto',
    category: 'Amparo',
    title: 'Demanda de amparo indirecto',
    description: 'Plantilla para demanda de amparo indirecto.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar procedencia, competencia, plazos y autoridades responsables antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Ej. JUEZ DE DISTRITO EN MATERIA...' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: 'Dejar en blanco si es demanda inicial' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Amparo Indirecto' },
      { id: 'quejoso', title: 'Quejoso', type: 'text', required: true, placeholder: 'Nombre del quejoso' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Describir personalidad o representación' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio para oír y recibir notificaciones' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'tercero_interesado', title: 'Tercero interesado', type: 'repeatable', required: false, repeatLabel: 'Agregar tercero interesado' },
      { id: 'autoridades_responsables', title: 'Autoridades responsables', type: 'repeatable', required: true, repeatLabel: 'Agregar autoridad responsable' },
      { id: 'acto_reclamado', title: 'Acto reclamado', type: 'textarea', required: true, placeholder: '[PENDIENTE: describir acto reclamado]' },
      { id: 'fecha_conocimiento', title: 'Fecha de conocimiento del acto', type: 'text', required: true, placeholder: 'DD/MM/AAAA' },
      { id: 'antecedentes', title: 'Antecedentes', type: 'textarea', required: false, placeholder: 'Bajo protesta de decir verdad...' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: 'Preceptos constitucionales violados' },
      { id: 'derechos_violados', title: 'Derechos y preceptos violados', type: 'textarea', required: true, placeholder: '[PENDIENTE: identificar derechos y preceptos aplicables]' },
      { id: 'conceptos_violacion', title: 'Conceptos de violación', type: 'repeatable', required: true, repeatLabel: 'Agregar concepto de violación' },
      { id: 'suspension', title: 'Suspensión', type: 'textarea', required: false, placeholder: 'Solicitud de suspensión' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Ej. Ciudad de México, a 26 de julio de 2026' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Nombre y firma del quejoso' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'suspension-amparo',
    category: 'Amparo',
    title: 'Solicitud de suspensión provisional y definitiva',
    description: 'Incidente de suspensión en amparo.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar procedencia, requisitos, efectos solicitados y circunstancias del caso antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez de Distrito...' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: 'Número de expediente' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Incidente de Suspensión' },
      { id: 'quejoso', title: 'Quejoso', type: 'text', required: true, placeholder: 'Nombre del quejoso' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que promueve' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'tercero_interesado', title: 'Tercero interesado', type: 'repeatable', required: false, repeatLabel: 'Agregar tercero interesado' },
      { id: 'autoridades_responsables', title: 'Autoridades responsables', type: 'repeatable', required: true, repeatLabel: 'Agregar autoridad responsable' },
      { id: 'acto_reclamado', title: 'Acto reclamado', type: 'textarea', required: true, placeholder: '[PENDIENTE: describir acto reclamado]' },
      { id: 'antecedentes', title: 'Antecedentes', type: 'textarea', required: false, placeholder: '[PENDIENTE: describir antecedentes relevantes]' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'suspension', title: 'Suspensión', type: 'textarea', required: true, placeholder: 'Solicito se conceda la suspensión provisional y en su momento la definitiva...' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Ciudad, fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'revision-amparo',
    category: 'Amparo',
    title: 'Recurso de revisión en amparo',
    description: 'Recurso de revisión.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['[PENDIENTE: verificar plazo, procedencia y autoridad competente antes de presentar]'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Tribunal Colegiado de Circuito en turno' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Número de amparo del que deriva' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Recurso de Revisión' },
      { id: 'promovente', title: 'Promovente', type: 'text', required: true, placeholder: 'Nombre del recurrente' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que promueve' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'tercero_interesado', title: 'Tercero interesado', type: 'repeatable', required: false, repeatLabel: 'Agregar tercero interesado' },
      { id: 'autoridades_responsables', title: 'Autoridades responsables', type: 'repeatable', required: false, repeatLabel: 'Agregar autoridad responsable' },
      { id: 'antecedentes', title: 'Antecedentes', type: 'textarea', required: false, placeholder: 'Resolución que se recurre' },
      { id: 'agravios', title: 'Agravios', type: 'repeatable', required: true, repeatLabel: 'Agregar agravio' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Ciudad, fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'queja-amparo',
    category: 'Amparo',
    title: 'Recurso de queja',
    description: 'Recurso de queja en materia de amparo.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['[PENDIENTE: verificar plazo, procedencia y autoridad competente antes de presentar]'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Tribunal Colegiado de Circuito' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Amparo o incidente' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Recurso de Queja' },
      { id: 'promovente', title: 'Promovente', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'tercero_interesado', title: 'Tercero interesado', type: 'repeatable', required: false, repeatLabel: 'Agregar tercero interesado' },
      { id: 'autoridades_responsables', title: 'Autoridades responsables', type: 'repeatable', required: false, repeatLabel: 'Agregar autoridad responsable' },
      { id: 'antecedentes', title: 'Antecedentes', type: 'textarea', required: false, placeholder: 'Acuerdo impugnado' },
      { id: 'agravios', title: 'Agravios', type: 'repeatable', required: true, repeatLabel: 'Agregar agravio' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Ciudad, fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'demanda-ordinaria-civil',
    category: 'Civil',
    title: 'Demanda ordinaria civil',
    description: 'Demanda para la vía ordinaria civil.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar legislación procesal vigente, competencia, vía, prestaciones y anexos antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'C. JUEZ DE LO CIVIL EN TURNO' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: 'Dejar en blanco' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Juicio Ordinario Civil' },
      { id: 'via_competencia', title: 'Vía procesal y competencia', type: 'textarea', required: true, placeholder: '[PENDIENTE: justificar vía y competencia aplicables]' },
      { id: 'actor', title: 'Actor', type: 'text', required: true, placeholder: 'Nombre del actor' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Si promueve por propio derecho o representación' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'demandado', title: 'Parte demandada', type: 'repeatable', required: true, repeatLabel: 'Agregar demandado' },
      { id: 'prestaciones', title: 'Prestaciones', type: 'repeatable', required: true, repeatLabel: 'Agregar prestación' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: 'Normas que sustentan la demanda' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Ciudad, fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'contestacion-civil',
    category: 'Civil',
    title: 'Contestación de demanda civil',
    description: 'Escrito de contestación de demanda en la vía ordinaria civil.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar plazo, cargas procesales, defensas, excepciones y respuesta a cada hecho antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Número de expediente' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Contestación a Juicio Ordinario Civil' },
      { id: 'promovente', title: 'Demandado', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que comparece' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'contraparte', title: 'Contraparte', type: 'text', required: true, placeholder: 'Nombre de la parte actora' },
      { id: 'contestacion_prestaciones', title: 'Contestación a las prestaciones', type: 'repeatable', required: true, repeatLabel: 'Agregar contestación a prestación' },
      { id: 'contestacion_hechos', title: 'Contestación a los Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar contestación a hecho' },
      { id: 'excepciones', title: 'Excepciones y Defensas', type: 'textarea', required: false, placeholder: 'Excepciones' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: 'Leyes' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar, fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'demanda-alimentos',
    category: 'Familiar',
    title: 'Demanda de alimentos',
    description: 'Juicio por pago de pensión alimenticia.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar legitimación, necesidades, capacidad económica, medidas solicitadas y pruebas antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'C. JUEZ DE LO FAMILIAR' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: '' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Controversia del Orden Familiar (Alimentos)' },
      { id: 'actor', title: 'Actor', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'relacion_acreedores', title: 'Relación con los acreedores alimentarios', type: 'textarea', required: true, placeholder: 'Describir parentesco, filiación o vínculo jurídico' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'En representación de menores, etc.' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'demandado', title: 'Demandado', type: 'repeatable', required: true, repeatLabel: 'Agregar demandado' },
      { id: 'prestaciones', title: 'Prestaciones', type: 'repeatable', required: true, repeatLabel: 'Agregar prestación' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'capacidad_economica', title: 'Capacidad económica del deudor', type: 'textarea', required: true, placeholder: 'Ingresos, actividad, bienes y demás datos comprobables' },
      { id: 'necesidades_especificas', title: 'Necesidades específicas de los acreedores', type: 'textarea', required: true, placeholder: 'Gastos de alimentación, salud, educación, vivienda y otros' },
      { id: 'medidas_provisionales', title: 'Medidas provisionales', type: 'textarea', required: false, placeholder: 'Solicitud de pensión provisional' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: 'Artículos' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'convenio-alimentos',
    category: 'Familiar',
    title: 'Convenio de alimentos',
    description: 'Propuesta de convenio sobre alimentos.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['[PENDIENTE: verificar requisitos de aprobación, ratificación y ejecución del convenio]'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez de lo Familiar' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Número de expediente' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Presentación de Convenio' },
      { id: 'promoventes', title: 'Partes (Promoventes)', type: 'text', required: true, placeholder: 'Nombres de las partes' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que comparecen' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio para oír y recibir notificaciones' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'antecedentes', title: 'Antecedentes', type: 'textarea', required: false, placeholder: '[PENDIENTE: describir antecedentes relevantes]' },
      { id: 'clausulas', title: 'Cláusulas del Convenio', type: 'repeatable', required: true, repeatLabel: 'Agregar cláusula' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: '[PENDIENTE: verificar fundamento aplicable]' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTAMOS LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Ciudad y fecha' },
      { id: 'firmas', title: 'Firmas', type: 'textarea', required: true, placeholder: 'Nombres y firmas de las partes' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'guarda-custodia',
    category: 'Familiar',
    title: 'Guarda y custodia',
    description: 'Juicio sobre guarda y custodia de menores.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar competencia, medidas solicitadas, contexto familiar y protección integral de niñas, niños o adolescentes.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'C. JUEZ DE LO FAMILIAR EN TURNO' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: '' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Controversia del Orden Familiar (Guarda y Custodia)' },
      { id: 'actor', title: 'Actor', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: '' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'demandado', title: 'Demandado', type: 'repeatable', required: true, repeatLabel: 'Agregar demandado' },
      { id: 'prestaciones', title: 'Prestaciones', type: 'repeatable', required: true, repeatLabel: 'Agregar prestación' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'medidas_provisionales', title: 'Medidas provisionales', type: 'textarea', required: false, placeholder: 'Solicitud de custodia provisional' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: '' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'regimen-convivencia',
    category: 'Familiar',
    title: 'Régimen de convivencia',
    description: 'Solicitud o demanda de régimen de visitas y convivencias.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar competencia, condiciones del régimen propuesto y protección integral de niñas, niños o adolescentes.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: '' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Régimen de Convivencia' },
      { id: 'actor', title: 'Actor', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'demandado', title: 'Demandado', type: 'repeatable', required: true, repeatLabel: 'Agregar demandado' },
      { id: 'prestaciones', title: 'Prestaciones', type: 'repeatable', required: true, repeatLabel: 'Agregar prestación' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'propuesta_regimen', title: 'Propuesta de Régimen', type: 'textarea', required: false, placeholder: 'Horarios propuestos' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: '' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'ejecutiva-mercantil',
    category: 'Mercantil',
    title: 'Demanda ejecutiva mercantil basada en pagaré',
    description: 'Juicio ejecutivo mercantil para cobro de pagaré.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar vía, exigibilidad, prescripción, documento base y anexos antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'C. JUEZ DE LO CIVIL O MERCANTIL EN TURNO' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: false, placeholder: '' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Juicio Ejecutivo Mercantil' },
      { id: 'via_procedencia', title: 'Vía y procedencia de la acción ejecutiva', type: 'textarea', required: true, placeholder: '[PENDIENTE: justificar procedencia y exigibilidad]' },
      { id: 'actor', title: 'Endosatario en Procuración / Actor', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Endosatario o Beneficiario' },
      { id: 'titulo_credito', title: 'Título de crédito y datos de identificación', type: 'textarea', required: true, placeholder: 'Tipo, número, lugar de suscripción y documento base' },
      { id: 'fecha_titulo', title: 'Fecha del título de crédito', type: 'date', required: true },
      { id: 'monto_titulo', title: 'Monto del título', type: 'number', required: true, placeholder: 'Monto y moneda' },
      { id: 'firmantes_titulo', title: 'Firmantes del título', type: 'text', required: true, placeholder: 'Suscriptor, avalista, endosantes u otros' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'demandado', title: 'Demandado', type: 'repeatable', required: true, repeatLabel: 'Agregar demandado' },
      { id: 'prestaciones', title: 'Prestaciones (Suerte Principal e Intereses)', type: 'repeatable', required: true, repeatLabel: 'Agregar prestación' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: 'Código de Comercio y LGTOC' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'contestacion-mercantil',
    category: 'Mercantil',
    title: 'Contestación ejecutiva mercantil',
    description: 'Contestación a demanda en la vía ejecutiva mercantil.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['[PENDIENTE: verificar plazo, defensas, excepciones y pruebas admisibles antes de presentar]'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Número de expediente' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Contestación Juicio Ejecutivo Mercantil' },
      { id: 'promovente', title: 'Demandado', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que comparece' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'contraparte', title: 'Contraparte', type: 'text', required: true, placeholder: 'Nombre de la parte actora' },
      { id: 'contestacion_prestaciones', title: 'Contestación a las prestaciones', type: 'repeatable', required: true, repeatLabel: 'Agregar contestación a prestación' },
      { id: 'contestacion_hechos', title: 'Contestación a los Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar contestación a hecho' },
      { id: 'excepciones', title: 'Excepciones y Defensas', type: 'textarea', required: false, placeholder: '[PENDIENTE: describir defensas y verificar su fundamento aplicable]' },
      { id: 'fundamentos_juridicos', title: 'Fundamentos jurídicos', type: 'textarea', required: false, placeholder: '' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar, fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'revocacion-fiscal',
    category: 'Administrativo/Fiscal',
    title: 'Recurso de revocación fiscal',
    description: 'Recurso de revocación ante autoridades fiscales (SAT, etc.).',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar procedencia, plazo, autoridad, medio de presentación y expediente administrativo antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Administración Desconcentrada Jurídica...' },
      { id: 'expediente', title: 'Expediente / Asunto', type: 'text', required: false, placeholder: 'Número de crédito fiscal o resolución' },
      { id: 'tipo_procedimiento', title: 'Tipo de procedimiento', type: 'text', required: false, placeholder: 'Recurso de Revocación' },
      { id: 'promovente', title: 'Promovente', type: 'text', required: true, placeholder: 'Nombre o razón social' },
      { id: 'personalidad', title: 'Personalidad / Representante', type: 'textarea', required: false, placeholder: 'Representante legal' },
      { id: 'domicilio_procesal', title: 'Domicilio para notificaciones', type: 'text', required: true, placeholder: 'Domicilio y RFC' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada' },
      { id: 'resolucion_impugnada', title: 'Resolución impugnada', type: 'textarea', required: true, placeholder: 'Oficio y fecha de resolución' },
      { id: 'numero_resolucion', title: 'Número de resolución u oficio', type: 'text', required: true, placeholder: 'Número o clave del acto' },
      { id: 'fecha_resolucion', title: 'Fecha de resolución', type: 'date', required: true },
      { id: 'autoridad_emisora', title: 'Autoridad emisora', type: 'text', required: true, placeholder: 'Autoridad que emitió la resolución' },
      { id: 'hechos', title: 'Hechos', type: 'repeatable', required: true, repeatLabel: 'Agregar otro hecho' },
      { id: 'agravios', title: 'Agravios', type: 'repeatable', required: true, repeatLabel: 'Agregar agravio' },
      { id: 'pruebas', title: 'Pruebas', type: 'repeatable', required: false, repeatLabel: 'Agregar otra prueba' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' }
    ]
  },
  {
    id: 'autorizacion-abogados',
    category: 'General',
    title: 'Promoción para autorizar abogados',
    description: 'Escrito libre para autorizar profesionales del derecho para oír y recibir notificaciones.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar alcance de la autorización y fundamento específico del procedimiento antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez...' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Número de expediente' },
      { id: 'tipo_procedimiento', title: 'Vía y procedimiento', type: 'text', required: true, placeholder: '[PENDIENTE: identificar vía y procedimiento]' },
      { id: 'promovente', title: 'Promovente', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que comparece' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio para oír y recibir notificaciones' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: true, repeatLabel: 'Agregar persona autorizada' },
      { id: 'cuerpo_escrito', title: 'Cuerpo del escrito', type: 'textarea', required: true, placeholder: '[PENDIENTE: describir alcance de las autorizaciones solicitadas]' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  },
  {
    id: 'copias-certificadas',
    category: 'General',
    title: 'Solicitud de copias certificadas',
    description: 'Escrito para solicitar copias certificadas y devolución de documentos originales.',
    legalBasis: pendingLegalBasis,
    applicableLaws: [...pendingApplicableLaws],
    warnings: ['Verificar fundamento, alcance, costo, destinatario y requisitos de entrega antes de presentar.'],
    disclaimer: commonDisclaimer,
    exportFormats: ['docx', 'pdf', 'text'],
    sections: [
      { id: 'autoridad_competente', title: 'Autoridad competente', type: 'text', required: true, placeholder: 'Juez...' },
      { id: 'expediente', title: 'Expediente', type: 'text', required: true, placeholder: 'Número de expediente' },
      { id: 'tipo_procedimiento', title: 'Vía y procedimiento', type: 'text', required: true, placeholder: '[PENDIENTE: identificar vía y procedimiento]' },
      { id: 'promovente', title: 'Promovente', type: 'text', required: true, placeholder: 'Nombre' },
      { id: 'personalidad', title: 'Personalidad', type: 'textarea', required: false, placeholder: 'Carácter con el que comparece' },
      { id: 'domicilio_procesal', title: 'Domicilio procesal', type: 'text', required: true, placeholder: 'Domicilio para oír y recibir notificaciones' },
      { id: 'personas_autorizadas', title: 'Personas autorizadas', type: 'repeatable', required: false, repeatLabel: 'Agregar persona autorizada para recoger copias' },
      { id: 'cuerpo_escrito', title: 'Documentos y alcance de la solicitud', type: 'textarea', required: true, placeholder: '[PENDIENTE: identificar documentos, actuaciones y alcance de las copias solicitadas]' },
      { id: 'puntos_petitorios', title: 'Puntos petitorios', type: 'repeatable', required: true, repeatLabel: 'Agregar punto petitorio' },
      { id: 'protesta', title: 'Protesta', type: 'text', required: true, placeholder: 'PROTESTO LO NECESARIO' },
      { id: 'lugar_fecha', title: 'Lugar y fecha', type: 'text', required: true, placeholder: 'Lugar y fecha' },
      { id: 'firma', title: 'Firma', type: 'text', required: true, placeholder: 'Firma' },
      { id: 'lista_anexos', title: 'Lista de anexos', type: 'repeatable', required: false, repeatLabel: 'Agregar anexo' }
    ]
  }
];

export const PROFESSIONAL_TEMPLATES = templates;
